### ISSUE TITLE
Use ocramius/package-version to purge the cache when the graphqlite version is updated

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/graphqlite#100]
The cache can be incompatible between GraphQLite versions.

We should ensure that the cache is automatically invalidated each time a new version of GraphQLite is installed.

We can do that by using @Ocramius's package-version package and use the package-version as a namespace for the cache.

Note: all PSR-16 caches do not have a notion of "namespace". If we want to be able to target all PSR-16 caches, we might need to write an adapter for PSR-16 caches that adds a prefix to all the keys automatically.

**Comment by Ocramius** [comment]
Would rather pin to smaller supported version ranges than using a runtime check
