### ISSUE TITLE
Fix DateTime parameter passed in variable

### ISSUE THREAD

**Issue by spartaksun** [thecodingmachine/graphqlite#123]
Passing DateTime as a request variable causes an exception:
```
TypeError: DateTimeImmutable::__construct() expects parameter 1 to be string, object given
/Users/admin/Projects/graphqlite/src/Types/DateTimeType.php:44
/Users/admin/Projects/graphqlite/src/Types/ArgumentResolver.php:54
```
Passing the same value inline works good.
Fixes and tests are in pull-request: https://github.com/thecodingmachine/graphqlite/pull/124
Thanks!

**Comment by moufmouf** [comment]
Closed by #124.
Thanks @spartaksun !
