### ISSUE TITLE
Add a @InjectUser annotation

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/graphqlite#131]
Idea: add a @InjectUser annotation that allows injecting the current user in any query / mutation / field.

```php
/**
 * @InjectUser(for="$user")
 * @Query
 */
public function foo(User $user): string {
   // Do something with the user
}
```

**Comment by fezfez** [comment]
I think its a bad idea, its adding complexity for nothing, instead use DI.

```php
class MyQuery
{
    private $session;
    public function __construct(Session $session)
    {
        $this->session = $session;
    }

    /** @Query */
    public function getUser(): string
    {
       return $this->session->getUser()->getName();
    }
}
```

If you go this way, the graphqlite is going to turn into DIC, i think it's not design in this way.

**Comment by XPOL555** [comment]
Hi @moufmouf, is this the last issue needed for v4? I'm really interested in this project since i want to bundle into my laravel 6 application. Is there any estimate on when the v4 will be available? 

Thank you for your amazing work!

**Comment by gulien** [comment]
@XPOL555 don’t hesitate to use the « dev-master » version: it is really stable ;)

**Comment by moufmouf** [comment]
@XPOL555 I cannot really give you an estimate for v4 release but it is definitely soon (probably in November).
You can start using the 4.x-dev version. There will not be any breaking changes before 4.0 is released.

I only plan to fix #103, implement this feature and add a way to add a GraphQL field directly on a magic property (that could be useful to ease the integration with Eloquent)

**Comment by XPOL555** [comment]
@moufmouf @gulien great! Thank you guys!

**Comment by moufmouf** [comment]
@fezfez I still gave this a try (see #202).

I understand that you can clearly inject the "session" in your constructor and fetch the current user this way, but this is framework specific. And GraphQLite is framework agnostic.

I envision the possibility to create third party packages that would contain queries / mutations that could be used in any framework. Adding this `InjectUser` annotation allows me to access the current user, whatever the framework I'm using.
