### ISSUE TITLE
[Feature request] Named Query

### ISSUE THREAD

**Issue by fezfez** [thecodingmachine/graphqlite#154]
Currently the query name is get from the method name. 

I would like to get name with query  annotation instead.

In this way the public class api don't have to change when adding this package.

Sample:

```php
/** @Query(name=areYourCool) */
public function __invoke()
{
    return rand(0, 1) === 1 ? 'You\'re cool, man.' : 'Not cool, man.';
}
```

**Comment by moufmouf** [comment]
Hey @fezfez ,

Actually, your sample does work! :)
There is a "name" attribute you can use with `@Query` annotations:

```php
/** @Query(name="areYourCool") */
```

will generate a "areYouCool" query.
(you can also use that in mutations and fields).

Relevant documentation regarding annotations is here:

https://graphqlite.thecodingmachine.io/docs/annotations_reference#query-annotation

**Comment by fezfez** [comment]
@moufmouf : haha, my bad. thanks !
