### ISSUE TITLE
@Security annotation does not work on @Type entity

### ISSUE THREAD

**Issue by spartaksun** [thecodingmachine/graphqlite#163]
#164
This code throws an exception:
```php
use TheCodingMachine\GraphQLite\Annotations as GraphQLite;

/**
 * @GraphQLite\Type()
 */
class Product {
  /**
   * @GraphQLite\Field()
   * @GraphQLite\Security("this.check()")
   */
  public function getType(): string {
    return 'sale';
  }

  public function check(): bool {
    return $this->id > 0;
  }
}
```
After debugging, I noticed that `callable` inside`QueryFieldDescriptor` is set only for controllers.
I have tried to write my own middleware annotation, but I could not find a way to pass context (`this`).

Is there any way to have security validation depending on entity state?

Thanks!

An exception itself:
[Fri Oct 25 15:51:08 2019] Expected a value other than null.
[Fri Oct 25 15:51:08 2019] #0 backend/vendor/webmozart/assert/src/Assert.php(598): Webmozart\Assert\Assert::reportInvalidArgument('Expected a valu...')

#1 /backend/vendor/thecodingmachine/graphqlite/src/Middlewares/SecurityFieldMiddleware.php(88): Webmozart\Assert\Assert::notNull(NULL)
#2 /backend/vendor/thecodingmachine/graphqlite/src/Middlewares/Next.php(42): TheCodingMachine\GraphQLite\Middlewares\SecurityFieldMiddleware->process(Object(TheCodingMachine\GraphQLite\QueryFieldDescriptor), Object(TheCodingMachine\GraphQLite\Middlewares\Next))
#3 /backend/src/Middleware/AccessFieldMiddleware.php(50): TheCodingMachine\GraphQLite\Middlewares\Next->handle(Object(TheCodingMachine\GraphQLite\QueryFieldDescriptor))
#4 /backend/vendor/thecodingmachine/graphqlite/src/Middlewares/Next.php(42): CNG\Middleware\AccessFieldMiddleware->process(Object(TheCodingMachine\GraphQLite\QueryFieldDescriptor), Object(TheCodingMachine\GraphQLite\Middlewares\Next))
#5 /backend/vendor/thecodingmachine/graphqlite/src/Middlewares/FieldMiddlewarePipe.php(32): TheCodingMachine\GraphQLite\Middlewares\Next->handle(Object(TheCodingMachine\GraphQLite\QueryFieldDescriptor))
#6 /backend/vendor/thecodingmachine/graphqlite/src/FieldsBuilder.php(311): TheCodingMachine\GraphQLite\Middlewares\FieldMiddlewarePipe->process(Object(TheCodingMachine\GraphQLite\QueryFieldDescriptor), Object(class@anonymous))
#7 /backend/vendor/thecodingmachine/graphqlite/src/FieldsBuilder.php(136): TheCodingMachine\GraphQLite\FieldsBuilder->getFieldsByAnnotations(NULL, 'TheCodingMachin...', false, 'CNG\\Domain\\Enti...')
#8 /backend/vendor/thecodingmachine/graphqlite/src/Types/TypeAnnotatedObjectType.php(41): TheCodingMachine\GraphQLite\FieldsBuilder->getSelfFields('CNG\\Domain\\Enti...')
#9 /backend/vendor/webonyx/graphql-php/src/Type/Definition/FieldDefinition.php(90): TheCodingMachine\GraphQLite\Types\TypeAnnotatedObjectType::TheCodingMachine\GraphQLite\Types\{closure}()
#10 /backend/vendor/webonyx/graphql-php/src/Type/Definition/ObjectType.php(151): GraphQL\Type\Definition\FieldDefinition::defineFieldMap(Object(TheCodingMachine\GraphQLite\Types\TypeAnnotatedObjectType), Object(Closure))

**Comment by moufmouf** [comment]
Hey @spartaksun,

Interesting! Thanks for the report. 

I'm away from keyboard right now but I'll try to reproduce this with a unit test and fix this next week.

**Comment by moufmouf** [comment]
It took me more time than I anticipated but it should be fixed. I refactored the notion of "field middleware" to give an easier access to the resolver from the middleware.

Anyway, it should work now. Let me know it you are facing any trouble.
