### ISSUE TITLE
MapIterator is not usable with graphqlite

### ISSUE THREAD

**Issue by Kharhamel** [thecodingmachine/graphqlite#165]
Since we can return ResultIterators to graphqlite, we should be able to return mapIterators too since they are specific resultIterators.

**Comment by moufmouf** [comment]
Not sure what you mean.

MapIterator is an iterator, so you need to tell GraphQLite the exact type in the @return annotation, but this should work.

Something like this should work:

```php
/**
 * @Query
 * @return MapIterator|string[]
 */
public function test(): MapIterator
```
