### ISSUE TITLE
HTTP 500 Error default

### ISSUE THREAD

**Issue by oojacoboo** [thecodingmachine/graphqlite#173]
I'd like to suggest that the default for `ClientAware` exceptions follow the HTTP standards.  As it is now, exceptions that implement the `ClientAware` interface are returning a 500 HTTP response code by default.

5** level response codes are reserved for server side errors.  Since we are notifying the client of an error, it's almost certainly the case that it's a client based error.  Otherwise, notification of the error details to the client is useless - the client cannot do anything about it.

Therefore, I'd like to see 4** level response codes for all exceptions implementing the `ClientAware` interface.  If there is a way to provide more contextually relevant response codes based on the exception being thrown, that'd be great.  I'll assume that this information is difficult to ascertain or futile.  In which case, I'd simply recommend making it a generic `400` response.

**Comment by moufmouf** [comment]
Hey @oojacoboo ,

> 5** level response codes are reserved for server side errors. Since we are notifying the client of an error, it's almost certainly the case that it's a client based error. Otherwise, notification of the error details to the client is useless - the client cannot do anything about it.

That's a quite interesting comment!

For the record, if an exception as a code between 400 and 599, it is used as an HTTP code for the response. So it is fairly easy to create a "ClientAware" exception that throws a 400.

That being said, the more I think about it, the more what you say makes sense. The default HTTP code for a "ClientAware" exception that has no exception code set should indeed by a generic `400` response.

For the record, we would need to change the "HttpCodeDecider" class here : https://github.com/thecodingmachine/graphqlite/blob/master/src/Http/HttpCodeDecider.php
