### ISSUE TITLE
[Semantical Error] Annotation @Autowire is not allowed to be declared on class

### ISSUE THREAD

**Issue by oojacoboo** [thecodingmachine/graphqlite#177]
>[Semantical Error] Annotation @Autowire is not allowed to be declared on class Foo. You may only use this annotation on these code elements: METHOD.

Trying to use the following annotation on the class

`@SourceField(name="company", annotations={@Autowire(for="$con")})`

`public function getCompany(ConnectionInterface $con = null)`

This is necessary since Propel, the ORM we use, takes in the connection object in order to hydrate a relational object, if needed - lazy loading.

**Comment by moufmouf** [comment]
Hey @oojacoboo ,

Thanks a lot for this bug report!
This was fixed in #195. You should now be able to use @Autowire (and absolutely all the other annotations) in a @SourceField annotation.
