### ISSUE TITLE
Explicit or implicit null on optional mutation argument not distinguishable

### ISSUE THREAD

**Issue by flow-control** [thecodingmachine/graphqlite#179]
Hey there,

first of all, thanks for this amazing library! :+1: 

i was wondering if there is a solutions to this problem we face and if you can help me or would accept a pull request for this.

**Problem:** Partially updates using mutations.

Lets assume we have a blog post and we would like to update the title of that specific blog post. I would have a factory for the Input type like this:

```php
class FooFactory {
    /**
     * @Factory()
     */
    public function createBlogPost(
        string $id,
        ?string $title = null,
        ?string $content = null
    ): BlogPost {
         // stuff to be done
    }
}
```

I want the client to be able to send a mutation like this one:

```graphql
mutation {
    blogPostUpdate(id: "id", title:"new title")
}
```

and only update the title and not touching the content. The problem i have is, that in the PHP method `createBlogPost` i can not distinguish between `$content` being set to `null` explicit in the mutation call or implicit by GraphQLite because it was optional and was not passed with the mutation.

**Possible solution**

All the information needed is already present in the resolver function (in GraphQLite v3 i looked it up in `src/QueryField.php:54-83`. We could pass the keys from `$args` to the `$method` if there is a type hint, or specific annotation, or something like that.

What do you think?

/Flo

**Comment by moufmouf** [comment]
Hey Flo!

This is quite specific, but in v4, I guess you could do that using a custom parameter middleware.

If I understand correctly, what you want is a `@InjectArgs` annotation that you could use like this:

```php
class FooFactory {
    /**
     * @Factory()
     * @InjectArgs(for="args")
     */
    public function createBlogPost(
        array $args,
        string $id,
        ?string $title = null,
        ?string $content = null,
    ): BlogPost {
         // stuff to be done
         // $args should contains all the arguments passed to the Webonyx resolver
    }
}
```

I would do this using a parameter middleware as described here: https://graphqlite.thecodingmachine.io/docs/next/argument-resolving

Using parameter middlewares, you can add your own custom annotations that modify the way parameters are resolved.

Do you feed like giving this a try?
Also, I'm not sure if this is a specific need or something that should be integrated in GraphQLite itself. If anyone else in interested in this feature, please leave a message below!

**Comment by flow-control** [comment]
Hey David,

i think you are right, this maybe a bit to specific to be handled in the library itself. The parameter middleware in `v4` should do the trick in this case :+1: 
As for now we are locked in `v3` (still on symfony 3), i wasn't looking at the `v4` documentation. But this is another point to the list, why we should give the update to symfony 4 more priority :wink: 

Thanks for your time and again, thanks for amazing library :tada: 

/Flo
