### ISSUE TITLE
Unable to install using composer for Symfony

### ISSUE THREAD

**Issue by brettins** [thecodingmachine/graphqlite#183]
The following command:
`composer require thecodingmachine/graphqlite-bundle`

gives me:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for thecodingmachine/graphqlite-bundle ^3.0 -> satisfiable by thecodingmachine/graphqlite-bundle[v3.0.0].
    - thecodingmachine/graphqlite-bundle v3.0.0 requires thecodingmachine/graphqlite ~3.0.0 -> satisfiable by thecodingmachine/graphqlite[v3.0.0, v3.0.1].
    - thecodingmachine/graphqlite v3.0.0 requires phpdocumentor/type-resolver ^0.4 -> satisfiable by phpdocumentor/type-resolver[0.4.0].
    - thecodingmachine/graphqlite v3.0.1 requires phpdocumentor/type-resolver ^0.4 -> satisfiable by phpdocumentor/type-resolver[0.4.0].
    - Conclusion: don't install phpdocumentor/type-resolver 0.4.0


Installation failed, reverting ./composer.json to its original content.
```

On Symonfy 4.3.4, PHP 7.2.24. Not sure what other information you need, or if I should be seeking help elsewhere. Thanks!

**Comment by moufmouf** [comment]
Hey @brettins ,

You should definitely try v4 that will be out in a few weeks.
It is pretty stable and has many many more features (and bugfixes).

Documentation is here: https://graphqlite.thecodingmachine.io/docs/next/features.html

Try installing it with: `composer require thecodingmachine/graphqlite-bundle ^4`
