### ISSUE TITLE
Add GraphQLite to graphql.github.io

### ISSUE THREAD

**Issue by alanpoulain** [thecodingmachine/graphqlite#186]
GraphQLite should be referenced in this page: https://graphql.org/code/#php.

A PR can be done here: https://github.com/graphql/graphql.github.io.

**Comment by moufmouf** [comment]
Hey Alan!

Damn'it, I never thought about it. Thanks a lot for the tip! :100: 

PR has just been opened: https://github.com/graphql/graphql.github.io/pull/797

**Comment by alanpoulain** [comment]
You're welcome :slightly_smiling_face:
API Platform has just been added so I thought about GraphQLite as well.
