### ISSUE TITLE
Unauthorized requests cannot fetch schema operations

### ISSUE THREAD

**Issue by oojacoboo** [thecodingmachine/graphqlite#197]
If the current user is not authorized for a particular operation, that operation (query or mutation) does not show as available in the `__schema`.  I'm noting that the `HideIfUnauthorized` annotation was recently added.  However, it seems this is the default.  

Am I missing something here?  Adding the `@Right` annotation to a query, which results in an `isAllowed() === false` return value from the auth service, causes the query to no longer be output in the `__schema`.

**Comment by moufmouf** [comment]
Hey @oojacoboo ,

Hiding the field was the default in GraphQLite 3, but in GraphQLite 4, the default is to show the field (and throw an error if access to this field is attempted).

Are you using GraphQLite 3 or GraphQLite 4?

**Comment by oojacoboo** [comment]
I'm using the latest master branch.  I'm referring to the `__schama`/docs, not a direct request to a field.  The fields don't show in the `__schema`.
