### ISSUE TITLE
Collection output type for field of GraphQL type

### ISSUE THREAD

**Issue by oojacoboo** [thecodingmachine/graphqlite#208]
So, assuming I have the following...

```php
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * User
 *
 * @GraphQLite\Type()
 */
class User
{

    protected Collection $tags;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    /**
     * Gets all the associated Tags.
     *
     * @GraphQLite\Field(outputType="[Tag]!")
     *
     * @return Tag[]
     */
    protected function getTags(): Collection
    {
        return $this->tags;
    }
}
```

How do I get this working?  I don't see anything in the docs covering this situation.  Do I need to make the Collection a GraphQL type and manage that Collection object?  In the case with Doctrine, this is managed by Doctrine directly.  I'm guessing maybe there is a way to have Doctrine use your own Collection class, provided that it implements the same interface, not sure though.

Can someone please direct me to some documentation or details on how to handle this scenario.  Thanks.

**Comment by oojacoboo** [comment]
UPDATE:

I'm not sure if I should be happy or upset that it took me nearly 2 hours to get this sorted...

Found the docs on this topic:
https://graphqlite.thecodingmachine.io/docs/next/type_mapping#array-mapping

Anyway, it does seem to work fine.  The `outputType="[Tag]!"` declaration in the annotation, however, causes GraphQLite, silently, to remove it from the schema.

I think the docs should be expanded slightly on this topic, but they are accurate.

**Comment by moufmouf** [comment]
Hey Jacob,

> I think the docs should be expanded slightly on this topic, but they are accurate.

Definitely agree.

> I think GraphQLite should complain or throw warnings, at the least, for more annotation issues, such as the outputType if it's not used, and annotations added to private or protected functions, causing them to be silently removed from the schema. This is obvious, but was overlooked and an error would have been really nice. This is just a downside to annotations. If it were standard PHP, you would have gotten a protected function access error.

I have already faced the issue.
It could be fairly easy to fix.... but it would slow down GraphQLite.

Code is here: https://github.com/thecodingmachine/graphqlite/blob/master/src/FieldsBuilder.php#L222

I'm scanning only the public functions for "@Field" annotations. Scanning also protected and private methods would slow down GraphQLite (or I would need to add a complex logic to do a sanity check and cache the sanity check result). Anyway, this part of GraphQLite is critical regarding performance and I chose the fastest route.

**Comment by oojacoboo** [comment]
@moufmouf Thanks, that totally makes sense.  We're actually caching everything on dev as well.  Annotations without cache, are just terribly slow in general.  Obviously, after clearing the cache, it'd still cause the next execution to be slower than it is now and I'm not sure I'd want that, it's already really slow.

In that case, I guess something could be added to the troubleshooting section in the docs.  I now know to look out for it and it's less of an issue.

Maybe what's really needed here is a new validator bin script that'd provide a way to scan all annotations, catch issues like this and even offer additional suggestions, tips, or validation errors going forward.  Doctrine has something like this that's very useful.

**Comment by moufmouf** [comment]
:+1: for the validation script. That will indeed be needed at some point.
