### ISSUE TITLE
MissingArgumentException exposes internals

### ISSUE THREAD

**Issue by oojacoboo** [thecodingmachine/graphqlite#211]
The `MissingArgumentException` exception returns the namespace of factories, methods called, etc.  ClientAware exceptions should not expose internals of the backend.  If it's necessary to provide this information to a developer, it should be thrown as an Exception, allowing exception handling to print to logs.

**Comment by moufmouf** [comment]
True :+1:

Ideally, I would like love to keep this information somewhere in "development mode".

Maybe something like:

```
{
  "errors": [
    {
      "message": "Expected argument 'XXX' was not provided"
      "extensions": {
        "inputType": "SomeInputType"
        "factory": "App\My\Factory"
      }
    }
  ]
}
```

The "extensions" section would be displayed only in "devMode", not in "prodMode".

**Comment by oojacoboo** [comment]
@moufmouf I think any information that is exposed through the API is appropriate to include in an error message.  This class, `MissingArgumentException`, as some additional data that is acceptable to be included in the message.  And, honestly, it probably sufficient.  However, additional contextual data within the extensions property, would also make sense in a "development mode".

`Excepted argument 'XXX' was not provided in GraphQL input type 'SomeInputType' in GraphQL query/mutation/field 'some'.`

The parts that show the factory class, decorator, or method name are internals that should not be exposed in the typical error message.

**Comment by moufmouf** [comment]
> Excepted argument 'XXX' was not provided in GraphQL input type 'SomeInputType' in GraphQL query/mutation/field 'some'.

Excellent error message. It provides all the information you can provide without exposing the internals. Thanks a lot, I'll use that!

**Comment by oojacoboo** [comment]
@moufmouf did this get implemented?
