### ISSUE TITLE
Return an array of different output types from mutation

### ISSUE THREAD

**Issue by oojacoboo** [thecodingmachine/graphqlite#212]
One recommended way to ensure better BC in the future for a GraphQL API, is to return an array/list with every mutation.  The benefit of this is that if you need additional output types for a mutation due to client needs, you can do so without breaking the API.  Consider the following:

```
sendMessage(body: "hello"): Message!
```

In this case you're updating a product and that's all fine.  But what if, later on, you need to return additional information, maybe a `queueId` for instance if you're using a more RPC style approach with message queueing.  Or any other variety of needs that might appear later on.

If you instead had the following:

```
sendMessage(body: "hello"): [Message!]!
```

Then, adding the `queueId` to the output type is very simple:

```
sendMessage(body: "hello"): [Message!, QueueId!]!
```

How would you go about doing this in GraphQLite?  I'm unable to find a good way of structuring things to support this.

**Comment by moufmouf** [comment]
I'm not sure I understand.

When you write:

```
[Message!, QueueId!]!
```

Is this valid GraphQL syntax?

Would you have a link to an article about best practices regarding ensuring better BC?

**Comment by oojacoboo** [comment]
@moufmouf `[Message!, QueueId!]!` is just pseudo code.  See Github's GraphQL API as an example of multiple return types.

https://developer.github.com/v4/mutation/updateenterprisememberscanupdateprotectedbranchessetting/
