### ISSUE TITLE
Install Causes Migrations namespace errors in Symfony

### ISSUE THREAD

**Issue by brettins** [thecodingmachine/graphqlite#216]
Hi, when I run 

`composer require thecodingmachine/graphqlite-bundle`

I get the following error:

```
Script cache:clear returned with error code 1
!!  
!!  In DebugClassLoader.php line 213:
!!                                                                                 
!!    The autoloader expected class "App\Migrations\[MigrationName]" to be   
!!    defined in file "[directory]/[MigrationName].php". The file was found but the class was not in it, 
!!    the class name or namespace probably has a typo.                               
!!                                                                                 

```

All subsequent symfony php commands result in the same error.

This is fixed by changing `namespace DoctrineMigrations` to `App\Migrations` in all the files, but this shouldn't be necessary - Migrations shouldn't be in the autoloader in the first place, and I'm unable to determine why they are included after install the graphqlite-bundle.

**Comment by moufmouf** [comment]
I see. Have a look at "graphqlite.yaml".

I think you must have something like:

```yaml
graphqlite:
      types: 
      - App\
```

GraphQLite will scan all classes in "App\". It will assume that all files respect PSR-4 (which is not true for migrations). Normally, it does not throw an exception if the class is not found. But in Symfony, there is this thing called "DebugClassLoader" that happens to throw exceptions a bit too eagerly.

I'll have to work on this.

In the meantime, you can change your config by restricting the "types" entry of the config file.
For instance:

```yaml
graphqlite:
      types: 
      - App\Entity
      - App\Types
```

You must put in the "types" key any namespace that contains classes that contain a `@Type` or a `@Factory` annotation.

**Comment by brettins** [comment]
That fixed it, thanks. Glad to hear you're working on it, as it's a litte odd that the install itself creates a config file that is incompatible with the default setup of a framework. 

I appreciate your time and hard work on this, as it will save me a lot of time!

**Comment by moufmouf** [comment]
Fixed!

Thanks for reporting the issue :)
