### ISSUE TITLE
Improve caching of GlobTypeMapper

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/graphqlite#22]
There must be a way to improve the performance of the GlobTypeMapper.
Currently, if globTtl is out (> 2s), all the annotations are parsed again. This is lengty (because for Factories, we scan each method of each class).

We could try to have an analysis that returns absolutely every file scanned, and another process that returns the SAME cache if none of the files that have been used for the cache have been modified.

Note: this might be tricky when calls to the recursive type mapper are involved. We might need to push that cache up to the recursive type mapper (if possible).

**Comment by oojacoboo** [comment]
@moufmouf Is this still an issue?
