### ISSUE TITLE
[Questions] Array input, any scalar type and pagination improvement

### ISSUE THREAD

**Issue by golaod** [thecodingmachine/graphqlite#23]
It's not a bug, but just a question. In my direct webonyx/graphql implementation, I had an abstract grid schema like:
```
myGrid(
  filters: {
    id: { operator: in /* enum */, value: [1, 2, 3] },
    name: { operator: like, value: '%test%' }
  },
  sorting: {
    date: asc /* enum */
  },
  limit: { page: 0, size: 15}
) {
  isFirst
  isLast
  currentSize
  totalSize
  rows {
    id
    name
    // etc
  }
}
```

Now my questions are whether same schema is possible to be achieved in graphqlite. It doesn't have to be one to one, but:
1. Can I add input which behaves like an array type of any scalar value?
2. Can I have default values for the input?
3. Can I extend what is displayed above rows, cause I saw in the documentation that you only return total size there
4. Eager loading (deferred resolvers). I know someone asked already about it
5. If those things are not possible, will they? and if they will, can we participate in development to speed things up?

**Comment by moufmouf** [comment]
Hey @golaod !

> 1. Can I add input which behaves like an array type of any scalar value?

Is this allowed by the GraphQL spec and Webonyx? My understanding is that union types can only be used on objects. Could you maybe post your Webonyx Input type? That would help me understand how to reproduce this.

> 2. Can I have default values for the input?

Yes, you simply put the default value in the method signature.

For instance:

```php
/**
 * @Factory
 */
public function filters(string $status = 'on'): Filter
```

> 3. Can I extend what is displayed above rows, cause I saw in the documentation that you only return total size there

You are referring to pagination with Porpaginas (https://graphqlite.thecodingmachine.io/docs/pagination), right?
It is possible, though not very simple.
What you want to do is to write your own "TypeMapper" that maps your class (in our case a class implementing the Porpaginas\ResultIterator interface) to a Webonyx Object type.

You can actually copy-paste the PorpaginasTypeMapper in your code and customize it.

https://github.com/thecodingmachine/graphqlite/blob/b997a25df4815dfb0e3489501f3783c62ec470c3/src/Mappers/PorpaginasTypeMapper.php

You then need to register the type mapper in your application. The way you do that depends on the framework you are using.

> 4. Eager loading (deferred resolvers). I know someone asked already about it

Not yet.
That will go in v3.1. See https://github.com/thecodingmachine/graphqlite/issues/14

I actually need help to find a simple syntax for deferred resolvers.

> 5. If those things are not possible, will they? and if they will, can we participate in development to speed things up?

Any help is definitely welcome! :)

**Comment by golaod** [comment]
We contacted you already by email to solve the problem for us, but because you asked here how we did any scalar, I'm attaching it for others who may need it:
```
Type::nonNull(Type::listOf(new AnyScalarType()))
```
And the type itself:
```
class AnyScalarType extends ScalarType
{
    const NAME = 'AnyScalar';

    const SCALAR_NODES = [
        StringValueNode::class,
        BooleanValueNode::class,
        IntValueNode::class,
        FloatValueNode::class
    ];

    /**
     * Serializes an internal value to include in a response.
     *
     * @param string $value
     * @return string
     */
    public function serialize($value)
    {
        return $value;
    }

    /**
     * Parses an externally provided value (query variable) to use as an input
     *
     * @param mixed $value
     * @return mixed
     */
    public function parseValue($value)
    {
        if (!is_scalar($value)) {
            throw new Error('Cannot represent following value as scalar: ' . Utils::printSafeJson($value));
        }

        return $value;
    }

    /**
     * Parses an externally provided literal value (hardcoded in GraphQL query) to use as an input.
     *
     * E.g.
     * {
     *   user(email: "user@example.com")
     * }
     *
     * @param \GraphQL\Language\AST\Node $valueNode
     * @return string
     * @throws Error
     */
    public function parseLiteral($valueNode)
    {
        $isScalar = false;
        foreach (self::SCALAR_NODES as $nodeClass) {
            if ($valueNode instanceof $nodeClass) {
                $isScalar = true;
                break;
            }
        }

        if (!$isScalar) {
            throw new Error("Not a valid scalar", [$valueNode]);
        }
        return $valueNode->value;
    }
}
```

**Comment by moufmouf** [comment]
For the record, this was fixed by various PRs in the last month.
Documentation is here: 

https://graphqlite.thecodingmachine.io/docs/next/custom-types#registering-a-custom-scalar-type-advanced
