### ISSUE TITLE
Duplicate input types created

### ISSUE THREAD

**Issue by oojacoboo** [thecodingmachine/graphqlite#237]
I'm unable to really track down how this is happening, but it's presenting issues with our schema.

The issue is when an input type is a field of another input type.  In these cases, it's mostly working correctly and represented correctly in the schema except it creates two input types.  Consider the following:

```php
class Factory
{
    /**
     * @Factory()
     */
    public function makeCreateCategory(string $name): CreateCategory {}

    /**
     * @Factory()
     */
    public function makeCreateProduct(
        string $name, 
        Money $price, 
        CreateCategory $createCategory
    ): CreateProduct {}
}
```

In this case above the `CreateCategory` will result in 2 input types in the schema, `CreateCategory` and `CreateCategoryInput`.

**Comment by moufmouf** [comment]
Weird! I would have expected it to fail....

You can have many `@Factory` returning the same type, but all of them expect one must be marked as "non-default" and a name must be explicitly given.

In your example, I would expect this to work:

```
class Factory
{
    /**
     * @Factory(default=true)
     */
    public function makeCreateCategory(string $name): CreateCategory {}

    /**
     * @Factory(default=true, name="SomeOtherName")
     */
    public function makeCreateProduct(
        string $name, 
        Money $price, 
        CreateCategory $createCategory
    ): CreateProduct {}
}
```

I'll write some more test cases to see how we can improve this.

Also, I'll be on holiday for the next week so do not be surprised if you don't get any news!

**Comment by oojacoboo** [comment]
@moufmouf enjoy your holiday!  We've got a hack in place for the moment, but noticed a lot of phantom output types in our schema as well - be great to get that cleaned up.
