### ISSUE TITLE
Laravel7 and graphqlite-laravel

### ISSUE THREAD

**Issue by mailopl** [thecodingmachine/graphqlite#244]
Any plans on supporting freshly released Laravel 7 soon? :)

**Comment by moufmouf** [comment]
Ho, definitely!

I don't have much time this end of week but I'll definitely try this, probably next week. If you have some spare time or are in a hurry, you can definitely propose a PR to upgrade to version 7. With a bit of luck, we will only need to update the `composer.json` :)

**Comment by moufmouf** [comment]
Done and tagged: https://github.com/thecodingmachine/graphqlite-laravel/releases/tag/v4.0.2

**Comment by mailopl** [comment]
Sweet! Thanks a lot! 🥇

**Comment by oneserv-heuser** [comment]
@moufmouf Can you please also update the [documentation](https://graphqlite.thecodingmachine.io/docs/laravel-package) as it says that the package is compatible with Laravel 5.7+ and 6.x and not with Laravel 7.

Thank you!
