### ISSUE TITLE
Feature Request: Field for property

### ISSUE THREAD

**Issue by Ciantic** [thecodingmachine/graphqlite#246]
I don't want to go all in with Java-like getters and setters. I want to treat my Dto's more like JSON objects thus I would like to define field in properties:

```php
class Product
{
    /**
     * @Field()
     */
    public int $id;

    /**
     * @Field()
     */
    public string $name = "";
}
```

I know that this is anti-pattern in OOP, but I don't care, my API is mostly readonly and I use the classes as a type safer alternative for typical spaghetti mixed array code.

I also don't seem to find a way to do this myself without forking graphqlite. The `MagicField`s are for classes, `Field` is for methods, and if I implement `FromSourceFieldsInterface` I should have to make another external class (it's not usable on the e.g. `Product` above directly.)

**Comment by oojacoboo** [comment]
We've made use of only properties with our input types.  It works well.  I know that's not the same thing, but I could see how this would be valuable.

**Comment by moufmouf** [comment]
Implementation pending in #269

**Comment by oojacoboo** [comment]
#269 is merged in now - closing this
