### ISSUE TITLE
Typed property must not be accessed before initialization

### ISSUE THREAD

**Issue by oojacoboo** [thecodingmachine/graphqlite#247]
```
Error: Typed property Foo::$bar must not be accessed before initialization

/srv/www/src/Foo.php:123
/srv/www/vendor/rentpost/graphqlite/src/Middlewares/SourceResolver.php:56
/srv/www/vendor/rentpost/graphqlite/src/QueryField.php:71
/srv/www/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php:632
```

Any thoughts on this?  The line in question looks like this:

```php
    protected int $bar;
  
    public function __construct(int $bar)
    {
        $this->bar = $bar;
    }

    public function getBar(): int
    {
        return $this->bar;
    }
```

Obviously I could set `$bar` to default as `NULL`, but that's not the goal here.  Why is GraphQLite trying to execute a method in this class without the constructor being called?

**Comment by oojacoboo** [comment]
So, the issue seems like it could be related to this class extending a base class that's a GraphQL type.  This particular class isn't included in any GraphQL logic, and didn't even have a `Type` annotation defined on it.  However, another class that extends the same parent, does have a `Type` annotation.  It also has the same method and property.  It seems like it's somehow calling this class as well.  I haven't dug into the internals enough to know what's going on.  It's strange, regardless.

**Comment by xpacman** [comment]
I also have this problem.

**Comment by oojacoboo** [comment]
@xpacman it's been a minute, but I believe this is a Doctrine issue related to hydration of new objects.  Closing this out.
