### ISSUE TITLE
Problem when install for first time

### ISSUE THREAD

**Issue by goxyed** [thecodingmachine/graphqlite#25]
Error regarding stability appears in fresh installation
thecodingmachine/graphqlite-bundle 3.0.x-dev requires thecodingmachine/graphqlite ^3 -> satisfiable by thecodingmachine/graphqlite[3.0.x-dev] but these conflict with your requirements or minimum-stability

**Comment by moufmouf** [comment]
GraphQLite is not yet tagged as 'stable'. It will be tagged this week or next week.

Meanwhile, you need to add in your composer.json:

```
{
    "prefer-stable": true,
    "minimum-stability": "dev"
}
```
