### ISSUE TITLE
SchemaFactory.getDoctrineAnnotationReader to always set debug=false

### ISSUE THREAD

**Issue by mailopl** [thecodingmachine/graphqlite#253]
So I'm troubleshooting performance at the moment and I found a possible bug.
There's a chance that the last parameter should be environment dependent. 

```
 $doctrineAnnotationReader = new CachedReader($doctrineAnnotationReader, $cache, false);
```

```
   /**
     * Returns a cached Doctrine annotation reader.
     * Note: we cannot get the annotation reader service in the container as we are in a compiler pass.
     */
    private function getDoctrineAnnotationReader(): Reader
    {
        if ($this->doctrineAnnotationReader === null) {
            AnnotationRegistry::registerLoader('class_exists');
            $doctrineAnnotationReader = new DoctrineAnnotationReader();

            $cache = function_exists('apcu_fetch') ? new ApcuCache() : new PhpFileCache(sys_get_temp_dir() . '/graphqlite.' . crc32(__DIR__));

            $namespace = substr(md5(Versions::getVersion('thecodingmachine/graphqlite')), 0, 8);
            $cache->setNamespace($namespace);

            $doctrineAnnotationReader = new CachedReader($doctrineAnnotationReader, $cache, false);

            return $doctrineAnnotationReader;
        }

        return $this->doctrineAnnotationReader;
    }
```

**Comment by mailopl** [comment]
Also GlobTypeMapper seems to set last parameter here as true (**useAutoloadDev**):
```
$this->classNameMapper     = $classNameMapper ?? ClassNameMapper::createFromComposerFile(null, null, true);
```

Looks like this could also be env dependent, making the resulting map much smaller in production.

**Comment by moufmouf** [comment]
Hey @mailopl ,

Thanks a lot for looking at performance!

Regarding `$doctrineAnnotationReader`, I'm not sure this will make a huge difference. Did you try it and did it make any difference at all?

The `getDoctrineAnnotationReader` method is called in the Symfony compiler pass. In production, this compiler pass is called only once. Then, the container is compiled and this code is never executed again.

Regarding `GlobTypeMapper` and `useAutoloadDev`, you certainly have a point!

By the way, what kind of performance are you getting right now and by how much are you looking to improve the perf?

**Comment by mailopl** [comment]
Hey! 

I'll get back to you with details (numbers perhaps) a little bit later. Right now I can tell that it feels like even though GraphQLite utilises the cache (tmp directory is created etc), it adds around 0.8-1s overhead (production settings, optimised auto-louder).

When It hits (laravel) **http middleware cache** that I created, the whole thing takes ~70ms with cached query.
On cache miss, it goes up to 900ms - 1200ms. Such overhead could indicate it analyses annotations once again. I need to investigate this further.

I also feel like there's some discrepancy in cache handling when on different environments (local vs production), although this may be result of me using still graphqlite-laravel that pulls GraphQLite without the last PR that got merged. 

So for sure there's some funky behaviour, but at this point I'm not sure how much of this is my fault and how much it's GraphQLite not liking me :D

**Comment by mailopl** [comment]
Ok, got some intel for you @moufmouf .

For context, I'm running PHP 7.4 laravel production server (fpm/nginx). Optimized autoloader. OPCache enabled (no preload). GraphQLite cache directory is created correctly in /tmp.

Whole request took 1600ms. I did set few checkpoints to measure, here's a list (ms):
getClassList: 91.050048828125
**buildMap**: 360.669921875
**getMaps**: 360.68994140625
**getMapClassToExtend**: 169.01000976562
**getMapClassToExtend**: 189.6298828125 _(called twice? means, null check fails twice?)_
nginx->laravel cache middleware hit: **60ms**
SQL query time: **20ms** 

When you sum function calls up, it's 1170ms. I could totally live with 200ms overhead when using cached schema, but here clearly something is not right. It looks like it does some extra work on every request.
I wish I could investigate more, but maybe for you it will ring a bell and I won't have to :P?

The way of time logging I used:

```
$start = round(microtime(true)*1000, 2);
$end = round(microtime(true)*1000, 2);
var_dump($end - $start);
```

**Comment by mailopl** [comment]
@moufmouf:

```
 /**
     * Returns an object mapping all types.
     */
    private function getMaps(): GlobTypeMapperCache
    {
        if ($this->globTypeMapperCache === null) {
            $this->globTypeMapperCache = $this->cacheContract->get('fullMapComputed', function () {
                return $this->buildMap();
            });
        }

        return $this->globTypeMapperCache;
    }
```

Looks like on my production server, cache contract misses fullMapComputed on every request and it needs to be calculated. Any idea why this might happen?

**Comment by moufmouf** [comment]
Sorry for the delay in answering this.
Thanks a lot for all the time you invest in finding this.
I'll give a look at it. I guess it must be Laravel specific (maybe the way I configure the Doctrine cache by default in Laravel?) When I do tests in Symfony, the cache is working well and I get results under 200ms once cache is loaded.

**Comment by moufmouf** [comment]
That may be a stupid question, but did you set `APP_ENV=production` in your .env file or your environment variables?
GraphQLite uses that to go in production mode and enable all the caches.

**Comment by mailopl** [comment]
There's no stupid questions. Yes I did set the env to production, also did run `php artisan optimise:clear && php artisan:optimise`. I even debugged it step by step (up to a point..), to be sure it's set correctly. But feels like somewhere, with production settings, the cache gets lost (because I was able to get ~200ms on dev too)

**Comment by moufmouf** [comment]
Started doing some tests.
Weirdly enough, in my case, the cache contract hits the `fullMapComputed` all the time.

But... when I purge the cache, the cache does not seem to be purged correctly...

I'll keep working on this.

**Comment by mailopl** [comment]
Also in my case it may be that graphqlite-laravel pulls:
`        "thecodingmachine/graphqlite": "^4",`
which is 4.0.2, and doesn't contain latest fixes.

**Comment by moufmouf** [comment]
Possibly. You can try to require "thecodingmachine/graphqlite": "^4.1" in your composer.json file.

If you have:

```
    "minimum-stability": "dev",
    "prefer-stable": true,
```

it will work and fetch the "master" branch.

In any case, cache purging seems to be broken. I've seen Laravel Cache implements PSR-16 since Laravel 6, so by dropping support for Laravel 5.x, I would be able to use directly Laravel Cache (rather than using Symfony Cache). I might aim for that in the GraphQLite 4.1.

**Comment by mailopl** [comment]
OMG, that's just a theory I will verify tomorrow, but it may be that..

**PhpFilesAdapter** uses **OPCode** cache (because it's available on my server). 
Nginx is configured so:
```
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
```
is passed, instead of:
```
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
```
[(official recommended configuration is the latter one)](https://www.nginx.com/resources/wiki/start/topics/recipes/symfony/)

I'm using symlinks and symlink path doesn't get properly resolved (when no $realpath_root is used), confusing opcode cache..

**Comment by mailopl** [comment]
Yup, now I'm down from ~1.6s to 600ms which means GraphQLite now takes ~500ms, laravel and queries ~100ms, and opcache failing did cost me ~1s.

Man, what an adventure.
