### ISSUE TITLE
Error extensions in "no framework" usage

### ISSUE THREAD

**Issue by mdoelker** [thecodingmachine/graphqlite#271]
Hi there,

first of all big thanks for providing this library which has been a big help and is a breeze to work with.

One thing I spent the last hour working on though which I think can benefit from some more documentation is the fact that we won't get custom error extensions displayed without the use of an explicitly set formatter. I eventually found #134 and the PR that adds this to the Laravel package, but it is not obvious at all, especially as the docs tell you that it should "just work".

So adding this to my bootstrap code, using the Webonyx StandardServer, made it work:
```php
$serverConfig->setErrorFormatter([WebonyxErrorHandler::class, 'errorFormatter']);
$serverConfig->setErrorsHandler([WebonyxErrorHandler::class, 'errorHandler']);
```

I think mentioning this in the "no framework" part of the documentation would be a big help for anybody like me trying to get it running standalone 👍 

Thanks!

**Comment by moufmouf** [comment]
Absolutely! I'll keep the issue open until I find some time to fix this. Thanks for notifying us!
