### ISSUE TITLE
Apply security annotations to type

### ISSUE THREAD

**Issue by gulien** [thecodingmachine/graphqlite#276]
It would be great if we could apply one ore more security annotations to a type directly.

For instance, we want to make sure that user details cannot be fetched by everyone.

Currently, you have to make sure that every mutations / queries / fields which return a `User` are secured.

But what if we could do the following:

```php
/**
 * @Type
 * @Right("FOO")
 * @Security(...) 
 */
class User
{
}
```

And then GraphQLite would automatically apply those annotations for every mutations / queries / fields which return a `User` (or an array of User).

**Comment by oojacoboo** [comment]
@gulien the best way to go about this, is to define your own authz service (function) that you can use with the `Security` annotation.  This is done by added a function to the Symfony `ExpressionLanguage`.

https://symfony.com/doc/current/components/expression_language/extending.html

At this point, you can design a function to take in whatever arguments you need for your authz needs.  We've written one that takes in various allowed roles.  But, you should design the function to work best with your business needs.
