### ISSUE TITLE
Nested query support

### ISSUE THREAD

**Issue by jensdenies** [thecodingmachine/graphqlite#278]
Hi,

First of all, thanks for the package, it's been a pleasure to work with. I've tried to search in the documentation and on Google, but i couldn't seem to find an answer. Actually, i'm not even sure if it's supported in the package, so that's why i'm opening this issue.

I'm trying to create a nested query in GraphQLite, to fetch some related data. I'm trying to achieve the following:

```
user {
    firstName
    lastName,
    orders(limit: 25) {
        orderId
    }
}
```

The `user` query would map to my controller. but i'm not sure about `orders`. Would it be a separate query on the controller or would i need to define it on the type?

**Comment by moufmouf** [comment]
Queries are only used on the top-level.

In your case, `orders` needs to be a field on the User type.

There are many ways you can add a field to the User type:

- You can simply use the @Field annotation on the `User` class
- You can use the `@ExtendType` annotation to build a service next to the `User` class that registers a field in it: https://graphqlite.thecodingmachine.io/docs/extend_type

In your case, I would probably try to use the @Field annotation in the User class and add a @Autowire annotation to reference the repository that does the request to fetch orders (see https://graphqlite.thecodingmachine.io/docs/autowiring)

So your code might look like this:

```php
class User {
    // ...

    /**
     * @Field
     * @Autowire(for="$repository")
     */
    public function getOrders(int $limit, OrdersRepository $repository) {
        return $repository->getOrdersForUser($this);
    }
}
```

(assuming you have a `OrdersRepository` that you use to access orders in your DB which is something you might have if you are using Doctrine).

Does it make sense?

**Comment by jensdenies** [comment]
@moufmouf Thanks you!
