### ISSUE TITLE
Cannot return null for non-nullable field

### ISSUE THREAD

**Issue by Lekkimone92** [thecodingmachine/graphqlite#280]
/**
     * @return Place[]|ResultIterator|null
     *
     * @Field()
     */
    public function getPlacesWithManagedRooms(): ?ResultIterator
    {
        return $this->placesWithManagedRooms;
    }
![image](https://user-images.githubusercontent.com/37795298/86745330-90e84a00-c03a-11ea-8dc3-265d73b79fc4.png)

**Comment by moufmouf** [comment]
Fixed! Will be available in v4.1
