### ISSUE TITLE
Using 2 prefetch methods with the same method signature causes the last one to unhandled.

### ISSUE THREAD

**Issue by jensdenies** [thecodingmachine/graphqlite#286]
Hey,

When there are 2 prefetch methods defined with exactly the same signature a conflict arises. In `QueryField.php` on line 107 the result will only store the result if it isn't set yet. Unfortunately, if two prefetch methods are defined with the same signature the computed hash will be the same and therefore the last prefetch method will not work.

## How to reproduce

In a type create two prefetch methods with the same signature and assign them to two fields. You can then request both of these fields and the value will be the same.

I've created a PR with a possible fix, but it might cause a possible breaking change since the methods are public: #287

**Comment by moufmouf** [comment]
Closed by #290
