### ISSUE TITLE
Safe + GraphQLite

### ISSUE THREAD

**Issue by homersimpsons** [thecodingmachine/graphqlite#288]
On a project I am using [Safe](https://github.com/thecodingmachine/safe) along side of GraphQLite.

As of Safe 1.0.0 `DateTimeImmutable` has been added to the library in order to overwrite some function that may failed "silently".

The problem is that GraphQLite do not handle this type of `DateTime`. It looks like the FQSen is hardcoded there:
https://github.com/thecodingmachine/graphqlite/blob/dd0861915658aa18b65f7f30cfd6a4399267a7ac/src/Mappers/Root/BaseTypeMapper.php#L142

Example to reproduce the bug:
```php
namespace App\Query;

use Safe\DateTimeImmutable;
use TheCodingMachine\GraphQLite\Annotations\Query;

class MyQuery
{
    /**
     * @Query()
     */
    public function myQuery(DateTimeImmutable $dateTimeImmutable): string
    {
        return 'It does not works';
    }
}
```

Reported issue:
```sh
For parameter $dateTimeImmutable, in App\Query::myQuery, cannot map class "Safe\DateTimeImmutable" to a known GraphQL input type. Check your TypeMapper configuration.
```

**Comment by oojacoboo** [comment]
You need to register a type mapper.  This isn't a case of being hardcoded really.  What's hardcoded here, is nothing more than a convenience for the PHP core `\DateTimeImmutable` class.

You're trying to use a custom class.  And that's okay, but you need to tell GraphQLite how to handle that.  I created a rather generic type mapper that's been working well for us.  I suggested having it implemented into the core with a config option to take in a mapping.  If this was completed, you'd have a very easy way to map this.  It looks like it's scheduled for 4.1 now.

Here is the original issue with the code if you'd like to go ahead and implement using your own custom type mapper...

https://github.com/thecodingmachine/graphqlite/issues/178
