### ISSUE TITLE
Array to InputType Syntax

### ISSUE THREAD

**Issue by brettins** [thecodingmachine/graphqlite#291]
Hi, I'm having trouble figuring out how to perform a mutation with an array of items as an InputType. The factory method is working properly, as I can correctly get an Item on the other side with the `item: {id: $itemId}` below. 

item & childItem are both of the same type, and i'm using a @param Item[] $childItems in Symfony to define the childItems. 

```
insertItem:`` gql` mutation insertItem(

    $itemId: Uuid!,
    $childItemIds: [Uuid!]!
) {
    insertItem(
        item: {id: $itemId},
        childItems:  { id: { in : { $childItemIds} }
    ){
       // ... stuff
    }
}
```

What is the syntax for getting the childItems here?

**Comment by brettins** [comment]
I asked around and it looks like there isn't a way to do this inline with GraphQL. So, I created an array of ItemInput before calling the mutation:
```
          for (var i = 0, len = item.childItems.length; i < len; i++) {
            childItems.push({ id : item.childItems[i].id } )
          }
```

The original query then became:
```
insertItem:`` gql` mutation insertItem(

    $itemId: Uuid!,
    $childItemIds: [ItemInput!]!
) {
    insertItem(
        item: {id: $itemId},
        childItems:  $childItemIds
    ){
       // ... stuff
    }
}
```
Once I understood that the `{id: $item}` wasn't a magic GQL/GraphQLite syntax and was simply an inline javascript object being created, the solution became fairly simple.

**Comment by drmax24** [comment]
is there an updated on this? Can I easily have an array input out of the box somehow?
