### ISSUE TITLE
Does GraphQLite support custom directives?

### ISSUE THREAD

**Issue by jensdenies** [thecodingmachine/graphqlite#296]
Hey,

Does GraphQLite support custom directives? Or is that something i'd have to configure within webonyx/graphql? I couldn't find any reference or mention to directives in the graphqlite codebase.

Spec:
https://graphql.org/learn/queries/#directives

**Comment by moufmouf** [comment]
Hey @jensdenies ,

Currently, GraphQLite provides no easy way to add custom directives. But that would be a great addition actually!

GraphQLite is based on Webonyx and Webonyx does support custom directives. So it should be possible to use custom directives right now. If you want to add a custom directive, right now, I think you need to do this:

- Create a custom directive class: https://webonyx.github.io/graphql-php/type-system/directives/
- Reference this directive in the GraphQL schema. The way you do this will depend on the framework you are using. For instance, if you are using Symfony, I would attempt to decorate the `SchemaConfig` class to add the custom directive
- Then, in your resolver, you should be able to type hint on `ResolveInfo`:

```php
/**
 * @Field
 */
public function getFoo(ResolveInfo $resolveInfo) {
    // According to the Webonyx documentation, the ResolveInfo object should contain information about the directive
    // To be perfectly honest, I don't know where and the Webonyx documentation does not specify it
}
```

I'll keep this issue open as it would be interesting to have a more "native" support to directives (maybe declaring a class with a @Directive annotation that mimics the way Doctrine annotations work in PHP?)

**Comment by jensdenies** [comment]
Hey @moufmouf,

Thank you for the reply. I've got it working now. I'd love to see native support for this sometime in the future.

**Comment by oojacoboo** [comment]
@jensdenies Please look into submitting a pull request for this if you're up for it.
