### ISSUE TITLE
Deprecation of fields not showing up in generated schema

### ISSUE THREAD

**Issue by oneserv-heuser** [thecodingmachine/graphqlite#302]
As written in the [docs](https://graphqlite.thecodingmachine.io/docs/next/type_mapping#deprecation-of-fields) I can add an deprecated tag to an field and it will then add the directive to the field in the schema. My guess is that the deprecated tag is than also added to the schema (see [graphql specs](https://spec.graphql.org/June2018/#sec-Field-Deprecation)) which is not the case.

I tried the example from the [docs ](https://graphqlite.thecodingmachine.io/docs/next/type_mapping#deprecation-of-fields)in an environment with PHP 7.3.22 and the Laravel package with version 4.0.2 and Laravel 7.26.1. Both fields were not marked as deprecated.

Is this intentional and just not implemented or a bug?

**Comment by oojacoboo** [comment]
Link to field deprecation in spec:
https://spec.graphql.org/June2018/#sec-Field-Deprecation

**Comment by oneserv-heuser** [comment]
This  feature was released in [4.1.0](https://github.com/thecodingmachine/graphqlite/releases/tag/v4.1.0) so I guess this issue is done.
