### ISSUE TITLE
Query complexity and query depth restriction

### ISSUE THREAD

**Issue by wwwroman5** [thecodingmachine/graphqlite#306]
Is there any way to restrict query complexity and depth. Something like that https://webonyx.github.io/graphql-php/security/

**Comment by mdoelker** [comment]
We can do that directly via webonyx's DocumentValidator

```php
DocumentValidator::addRule(new QueryDepth($maxQueryDepth));
DocumentValidator::addRule(new QueryComplexity($maxQueryComplexity));
```

**Comment by moufmouf** [comment]
If you are using Symfony, the next release (4.1) will offer settings for query complexity and depth:

https://graphqlite.thecodingmachine.io/docs/next/symfony-bundle-advanced#schema-and-request-security

**Comment by rsolyanik** [comment]
> If you are using Symfony, the next release (4.1) will offer settings for query complexity and depth:
> 
> https://graphqlite.thecodingmachine.io/docs/next/symfony-bundle-advanced#schema-and-request-security

it's great! In addition, for full use, needed a way to customize the calculation of complexity for specific fields. (annotation, i suppose). And it would be nice to have a way to set a custom default function for calculating field complexity if there is no rule for a specific field
