### ISSUE TITLE
Annotation cache dir is in /tmp if apcu is not used

### ISSUE THREAD

**Issue by MattBred** [thecodingmachine/graphqlite#309]
Related: #303 

In the SchemaFactory, it defaults to `sys_get_temp_dir()` if the apcu extension is not found:

```php
$cache = function_exists('apcu_fetch') ? new ApcuCache() : new PhpFileCache(sys_get_temp_dir() . '/graphqlite.' . crc32(__DIR__));
```

This cache dir should be configurable, so that for example, in a Symfony install, we can set it to `var/cache/dev`

**Comment by moufmouf** [comment]
Closed by #310
