### ISSUE TITLE
[Question] Returns all fields

### ISSUE THREAD

**Issue by cvergne** [thecodingmachine/graphqlite#324]
Hi,

First, thanks for this library & the bundle, really great :)

I've searched both here and on webonyx/graphql-php but no clue.
I know it's not something standard in GraphQL, but is there a (simple ?) way to returns all fields if no selection is given in a query, instead of none (_assuming the ScalarLeafs rule is not enabled_) ?

Thanks !

Edit: Note that i'm on Symfony, so using the symfony bundle of GraphQLite, if it can help

**Comment by oojacoboo** [comment]
That's not how GraphQL works.  Please refer to the GraphQL spec.  GraphQLite doesn't attempt to modify or change the GraphQL spec.  It follows it.
