### ISSUE TITLE
Cannot use mapping defined in vendor classes

### ISSUE THREAD

**Issue by tigitz** [thecodingmachine/graphqlite#333]
Hello guys,

I'm designing a monolithic app with splitted modules. I designed my types in `Company\Package1\DTO` and require them in my main symfony app `Company\App` like this:

```json
   "name": "company/app",
    "repositories": [
        {
            "type": "path",
            "url": "../../modules/shared",
            "options": {
                "symlink": true
            }
        },
        {
            "type": "path",
            "url": "../../modules/package1",
            "options": {
                "symlink": true
            }
        }
    ],
    "require": {
        "php": ">=8.0",

        "company/package1": "*",
        "company/shared": "*"
    },
    "autoload": {
        "psr-4": {
            "Company\\App\\": "src"
        }
    },
```

Unfortunately, with this symfony config it doesn't work: 
```yaml
graphqlite:
  namespace:
    controllers: Company\Apps\GraphqlController\
    types:
      - Company\Package1\Domain
```

With some digging I found out that `\TheCodingMachine\ClassExplorer\Glob\GlobClassExplorer::doGetClassMap` relies on declared namespaces in the `autoload` sections of the `composer.json` file. In my case it's the `company/app/composer.json` and obviously it doesn't redeclare the `Company\Package1` namespace in its autoload section as it's a dependency. So no mappings can be found in `Company\Package1\Domain`.

Is there any workaround for this issue ? I'm planning to use this lib extensively for my company core product so I'm inclined to contribute a solution if any guidance is provided.

Many thanks

**Comment by oojacoboo** [comment]
Did you get this sorted?  Why are you "requiring" them?  Why aren't you using the autoloader?  I'm a bit confused by your question.  At any rate, this isn't a GraphQLite issue as far as I can see, rather an autoloading setup issue.

**Comment by tigitz** [comment]
@oojacoboo Nope I haven't, I'm requiring them because I want my models (and therefore the related graphqlite attributes) to be reused in different apps. So I designed them in a single package and I require this package in multiple apps.

From my further investigation it seems to be a graphqllite symfony bundle problem rather actually. The way it tries to find models is based on the autoload namespace in the composer.json. I'll close this issue and open one in the symfony bundle repo and provide a reproducible example.
