### ISSUE TITLE
"Cannot query field" when getting relationships

### ISSUE THREAD

**Issue by meylisday** [thecodingmachine/graphqlite#335]
Hi, there. I need help to figure out how I can get relationships. I was following  [this](https://graphqlite.thecodingmachine.io/docs/next/laravel-package-advanced#pitfalls-to-avoid-with-eloquent) guide but I didn't reach success.

My customer model: 
```
/**
 * @Type()
 * @MagicField(name="cards", phpType="App\\Card")
 */
class Customer extends Authenticatable
{
    public function cards(): HasMany
    {
        return $this->hasMany(Card::class);
    }
}
```
I had the error 
`ReflectionException: Class \App\Models\App\\Card does not exist in file vendor/thecodingmachine/graphqlite/src/Mappers/Root/IteratorTypeMapper.php on line 64`

If I replace `phpType="App\\Card"` to `phpType="Card"` I get the error 
`BadMethodCallException: Method Illuminate\Database\Eloquent\Collection::getBrand does not exist. in file vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php on line 103`

My query: 
```
query authCustomer {
  authCustomer{
      firstName
      lastName
      email
      createdAt
      updatedAt
      username
    cards {
        brand
    }
  }
}
```
My card model:
```
/**
 * @Type()
 */
class Card extends Model
{
    public function customer(): BelongsTo
    {
        return $this->belongsTo(Customer::class);
    }
      /**
     * @Field()
     */
    public function getBrand(): string
    {
        return $this->brand;
    }
 }
```
I use laravel 8.

**Comment by oojacoboo** [comment]
I think you're missing a `use` statement in your class.  If that's not working for you, please try the FQCN.

**Comment by meylisday** [comment]
@oojacoboo I have the `use` statement for MagicField annotation 
`use TheCodingMachine\GraphQLite\Annotations\MagicField;`
Where should I use FQCN?

**Comment by oojacoboo** [comment]
The `use` statement is for `Card`

**Comment by meylisday** [comment]
> The `use` statement is for `Card`

@oojacoboo I added the use statement `use App\Models\Card;` but I still get error.

**Comment by meylisday** [comment]
I've figured out. Maybe it will helpful for someone. For hasMany relationships need to add php type as array. For example:
`@MagicField(name="cards", phpType="Card[]")`
