### ISSUE TITLE
How to print schema

### ISSUE THREAD

**Issue by darkiron** [thecodingmachine/graphqlite#346]
How to print schema? To connect graphiQL?
thanks :+1:

**Comment by oojacoboo** [comment]
GraphQL, the spec, defines the introspection query for access to your schema.  All GraphQL clients will default to using this.  If you're trying to configure your server for your API, I'm afraid that's outside the scope of this project.

**Comment by TamasSzigeti** [comment]
Or if you just want a full schema dump, get the `TheCodingMachine\GraphQLite\Schema` service (inject or get from container: use your framework), and pass it into `GraphQL\Utils\SchemaPrinter`. We do this for apollo codegen.
