### ISSUE TITLE
Compile Error: Cannot declare class XXController, because the name is already in use

### ISSUE THREAD

**Issue by darkiron** [thecodingmachine/graphqlite#347]
Hi, 

Have declared my `grapqlite.yaml` in Symfony

    # Read more about GraphQLite available options at: https://graphqlite.thecodingmachine.io/docs/symfony-bundle
   graphqlite:
     namespace:
       controllers: App\GraphqlController\
       types:
         - App\

I have created a controller ` GraphQLTestController` with simple hello function 

```
    #[Query]
    public function hello(string $name): string {
        return "hello $name";
    }
```

Who work well, after some problems ;)  
After I tried to create a new Controller Product (`ProductController`), since my project have crashed with the error:

>  Compile Error: Cannot declare class App\HttpController\GraphQLTestController, because the name is already in use

I already change namespace unsuccessfully, it's very strange error ;)

**Comment by oojacoboo** [comment]
This looks like a Symfony issue to me.  I'm guessing that compile error is related to your service container's complication pass.  Please make sure you're not registering this namespace twice.
