### ISSUE TITLE
Integration of ecodev/graphql-doctrine

### ISSUE THREAD

**Issue by raphaelvoisin** [thecodingmachine/graphqlite#349]
Hello all,

I would like to integrate https://github.com/Ecodev/graphql-doctrine in my PHP 8 graphqlite project.

Short aside : 
_Initially, I had a composer issue because only `graphq-doctrine 7.3` accepts PHP 8, but force "webonyx/graphql-php": "^14.3" (https://github.com/Ecodev/graphql-doctrine/blob/7.1.3/composer.json#L36), but current version of graphqlite is stuck at  "webonyx/graphql-php": "^0.13.4"._
However let's forget that for now, as I temporarily forked the graphq-doctrine repo to make the compatibility.

**My problem :** 
As you can see in https://github.com/Ecodev/graphql-doctrine/blob/master/README.md, provides a way to generate a set of   [`InputObjectType`](https://webonyx.github.io/graphql-php/type-system/input-types/#input-object-type) to represent doctrine filters to apply to an Entity :  
```php
$types->getFilter(Post::class) // returns an array of filters that can be applied to a doctrine queryBuilder
```
I'm looking for a way to integrate that to a query in my graphqlite project. It sounds like an [input type](https://graphqlite.thecodingmachine.io/docs/input-types), but doesn't really work the same (for graphqlite, `InputType` are user-custom classes, not the final graphql [`InputObjectType`](https://webonyx.github.io/graphql-php/type-system/input-types/#input-object-type) ).

Ideally, I would like to declare my controllers with something like this : 
```php

class SearchElementController
   
    // [ ... ]

    /**
     * @return Post[]
     */
    #[Query]
    public function searchForSomething(
        array $readyToUseDoctrineFilters
    ): array
    {
            $types = new GraphQL\Doctrine\Types($this->entityManager);
            $filteredEntities = $types->createFilteredQueryBuilder(Post::class, $readyToUseDoctrineFilters, []);
            return $filteredEntities
    }
}
```

So : 
- is it possible this way somehow ?
- should I try to dig into the `\TheCodingMachine\GraphQLite\SchemaFactory` to add my special types or even add/merge a seperated Schema ?
- should I try to dig into the internals (https://graphqlite.thecodingmachine.io/docs/internals) to add some special mapper logic ?

Any help / guidance will be appreciated :)

**Comment by oojacoboo** [comment]
Firstly, that lib is entirely unnecessary if you're using GraphQLite.  We use Doctrine and GraphQLite, ourselves.  Decide which one you want to use, but I don't see any value in trying to use both of these libs.

**Comment by raphaelvoisin** [comment]
The lib would be very useful mainly for that : https://github.com/Ecodev/graphql-doctrine#filtering-and-sorting :  
| It is possible to expose generic filtering for entity fields and their types to let users easily create and apply generic filters. This expose basic SQL-like syntax that should cover most simple cases.

This is basically what I want to do. How can I do that just with GraphQLite without re-making exactly what the lib provides (in other word, the job done in `$types->getFilter(Post::class)`) ?

**Comment by oojacoboo** [comment]
I'm not entirely certain on your use case here.  In general, the query or mutation will perform the necessary query logic.  If, beyond that, you're needing to filter, I've written an advanced multi-tenancy extension for Doctrine that'll probably do the trick.

https://github.com/rentpost/doctrine-multi-tenancy

The main idea behind this is, indeed, for multi-tenancy, however, we use this for role based filtering as well.  It's designed to be flexible.

**Comment by raphaelvoisin** [comment]
@oojacoboo Generally speaking, my use-case is to be able to easily expose some advanced filters on some of my entity fields, as a `search` query.

I had a look to your huge work in https://github.com/rentpost/doctrine-multi-tenancy, but I don't think it belongs to my objective.

Basically, it's quite easy to provide a simple `equals` filtering in graphQL with something like :  
```graphql
query {
  post(id: 1001) {
      id
      content
  }
}
```
-> that would simply return the `id` and `content` of the posts with `post.id=1001`

But I would like to go further and being able to do some complex filtering like this :
```graphql
query {
    post(Filter: {
        groupLogic: "OR",
        conditions: [
            {
                id: {
                    in: [1001, 1002]
                }
            },
            {
                content: {
                    like: "%term%"
                }
            }
        ]
    }) {
        id
        content
    }
}
```
-> that would return the `id` and `content` of the posts with `post.id IN (1001, 1002) OR content LIKE "%term%"` 

_Note that the following example above is not **exactly** the filter syntax proposed by graphql-doctrine (but close), this is just to illustrate_ 

- The complicated schema behind the `Filter` InputType is what `graphql-doctrine` provides with `$types->getFilter(Post::class)`. 
- The capability of adding the resolved PHP filters to a QueryBuilder is what `graphql-doctrine` provides with `(new GraphQL\Doctrine\Types($this->entityManager))->createFilteredQueryBuilder(Post::class, $readyToUseDoctrineFilters, [])`

**Comment by oojacoboo** [comment]
I'm just going to go out and say that I completely disagree with this syntax and the approach here.  An API isn't supposed to be a layer on top of SQL.  In this example, you're basically just exposing your db schema with an alternate SQL syntax.  

I think maybe it'd be more helpful if we used an actual example without the pseudo-code and I could either give you a reasonable option/approach/design using GraphQLite, or let you know what issues you might run into.

**Comment by oojacoboo** [comment]
This is totally doable.  I don't particularly like it though.  IMO, you'd be far better off, and the API would be more user-friendly, if you exposed each of these "filters" for each query as arguments, as is typically done.  In the long run, by doing so, you'll have better access to the individual filter criteria being passed to each query, allowing for you to add additional conditional validation, authz, etc.

That said, if you're adamant on going down this path, it shouldn't be that difficult.  Write a Filter class input type with the various fields/filter criteria and add that as an optional field for each query.  Then, in your controller or a base controller class if you like, check for the Filter input type, pass it to a service that converts it into Doctrine friendly query builder syntax, then pass that to your repository method that get's all posts - use it to add filtering criteria.

**Comment by oojacoboo** [comment]
Why not just use their query builder factory then, or take inspiration from it and pass that to your repository?

https://github.com/Ecodev/graphql-doctrine/blob/master/src/Factory/FilteredQueryBuilderFactory.php

IMO, trying to merge these together, in order to prevent doing custom coding work, is a terrible mistake.  A far better use of your time would be to pick one and bridge the gaps to fit your needs.
