### ISSUE TITLE
mapTTL seems to be not set by default and can't be configured

### ISSUE THREAD

**Issue by Lappihuan** [thecodingmachine/graphqlite#350]
mapTTL seems to be intended to controll the Cache of TypeMappers.

It is implemented up to the FactoryContext but the SchemaFactory is not exposing it, nor setting it, which leaves it null for ever.
From my understanding this could potentially be a performance boost on each request.

Is this intentional or an oversight?

**Comment by oojacoboo** [comment]
Would a `null` TTL value simply not expire the cache?  How would specifying a TTL value, which expires the cache, improve performance?

**Comment by Lappihuan** [comment]
I'm not sure, but that might be the case that a null value will cache forever.
It seems odd that the globTTL is always set but the mapTTL not.

**Comment by oojacoboo** [comment]
I don't have an  issue with, or see an issue, with exposing this property if you'd like to submit a PR.  Maybe @moufmouf can chime in on this.

**Comment by Lappihuan** [comment]
@oprypkhantc is this also obsolete with your new cache in #698?

**Comment by oprypkhantc** [comment]
Yep @Lappihuan

**Comment by oojacoboo** [comment]
Closed by #698
