### ISSUE TITLE
Is there a Command / service to get graphql schema

### ISSUE THREAD

**Issue by aszenz** [thecodingmachine/graphqlite#352]
I'm wondering if there's built in way to generate the whole graphql schema for the project, basically get the result of the introspection query programmatically without doing any request. 

Use case
Our frontend generator tool expects a graphql schema file to generate types, it would be great to have a command generate the schema file at build step. 

One solution which we are currently exploring is using a symfony command that triggers an introspection query manually with a fake request object.

**Comment by oojacoboo** [comment]
I'm not aware of any exposed API for accessing this.  We've written our integration tests by mocking a request object and pass it to the middleware.  This works well and there isn't a lot of overhead really since you're taking http out of the equation.

**Comment by TamasSzigeti** [comment]
Here you go https://github.com/thecodingmachine/graphqlite-bundle/pull/93

**Comment by aszenz** [comment]
> Here you go [thecodingmachine/graphqlite-bundle#93](https://github.com/thecodingmachine/graphqlite-bundle/pull/93)

Thanks that looks awesome, having a built in command is pretty useful.
