### ISSUE TITLE
Package doesn't work with deprecated Doctrine Cache 2.0

### ISSUE THREAD

**Issue by Cryszon** [thecodingmachine/graphqlite#353]
[Doctrine Cache](https://github.com/doctrine/cache) library is [deprecated](https://github.com/doctrine/cache/issues/354) and all implementations were removed in 2.0. Our friendly Dependabot [automatically updated](https://github.com/thecodingmachine/graphqlite/pull/343) the requirement to `doctrine/cache ^1.8 || ^2.0`, which means that GraphQLite stops working if version 2 of `doctrine/cache` is installed.

Suggested actions:
- Temporarily revert to `doctrine/cache ^1.8`
- **Refactor to another cache implementation**
- Carefully review major version bumps by Dependabot in the future to prevent BC breaks

**Comment by oojacoboo** [comment]
Thanks for bringing this to our attention @Cryszon.  I've temporarily reverted to version 1.8.  

Going forward, it's probably best that we refactor the cache implementation, being that `doctrine/cache` is deprecated.  I'm going to leave this issue open until that's been addressed.

**Comment by oojacoboo** [comment]
`symfony/cache` might be the best option when refactoring:  https://github.com/symfony/cache

**Comment by TamasSzigeti** [comment]
Given this package is trying to be framework-agnostic, I would recommend relying on PSR cache interfaces – currently there are 3 cache dependencies, would make sense to unify them all.
