### ISSUE TITLE
[Bug][Docs] Dead links in docs

### ISSUE THREAD

**Issue by bingalls** [thecodingmachine/graphqlite#356]
Consider running `linkchecker` or similar as part of your CI.
In particular, `https://graphqlite.thecodingmachine.io/docs/other-frameworks#integration` has a dead link for [Schema](https://web.archive.org/web/20200716035526/http://webonyx.github.io:80/graphql-php/type-system/schema/)

Other docs may be stale. For example, was ` container-interop/service-provider` deprecated 4 years ago by PSR-11 ?

**Comment by oojacoboo** [comment]
@bingalls Thanks for submitting this.  Our documentation has received a pretty large update and all dead links should be resolved now.  I've run it through `linkchecker`, wasn't aware of that tool - pretty cool.
