### ISSUE TITLE
Support for graphql enums using constant doc types

### ISSUE THREAD

**Issue by aszenz** [thecodingmachine/graphqlite#359]
In php community many users are using psalm and phpstan which support defining constant enums like this:

```php
/**
 * @return 'SUPER_ADMIN'|'ADMIN'|'USER'
 */
function getRole():string {
}
```

The same type can also be denoted using php constants and * suffix.

```php
const ROLE_SUPER_ADMIN = 'SUPER_ADMIN';
const ROLE_ADMIN = 'ADMIN';
const ROLE_USER = 'USER';

/**
 * @return ROLE_*
 */
function getRole():string {
}

```

I feel like this is a super light weight way of defining graphql enums without having to install any third party package so just wondering if it's possible to implement support for this.

Note php 8.1 is coming with native enums so if this seems unnecessary feel free to close this issue.

**Comment by oojacoboo** [comment]
I think we should wait on native enums.  I'm definitely not a fan of adding more annotation based logic.  I do agree enums could be handled better.  Hopefully after 8.1 we can make some improvements here.
