### ISSUE TITLE
File Upload Not Working 

### ISSUE THREAD

**Issue by sachingk** [thecodingmachine/graphqlite#363]
The file upload is not working. Gets following error message 

_GraphQL Request must include at least one of those two parameters: "query" or "queryId"_

**Client Side Inputs** 

_operations  :_
 "{
"query": "mutation($createAttachmentInput: createAttachmentInput!) {  createAttachment(input: $createAttachmentInput) {      id      contentUrl     createdAt     updatedAt       }}",
"variables":{"createAttachmentInput":{"file":null}},
}"

_map:_
{"0":["variables.createAttachmentInput.file"]}

_0:_ 
uploaded file 

**Please let me know, what wrong  am I doing ?**

**Comment by oojacoboo** [comment]
Hey @sachingk.  I'm not really sure based on your description.  Did you follow the docs and install the upload lib?

https://graphqlite.thecodingmachine.io/docs/file-uploads

We're currently using this lib and have uploads working for us.  You do need to be sure that the `UploadMiddleware` is processing your `ServerRequest` before handing it off to the `WebonyxGraphQLMiddleware`.

**Comment by sachingk** [comment]
Could you please let me know what must mutation should look like. Am I using the right syntax for there ?

**Comment by oojacoboo** [comment]
@sachingk GraphQLite follows the GraphQL spec.  You'll want to reference it for the proper syntax.

**Comment by sachingk** [comment]
File Upload is working. it's a mistake on my side. 

I sent a formatted query string with new line for easy readability (as written above) in `PostMan`. This was a mistake. 

The `UploadMiddleware`  use `json_decode` function and the string like above returns false. Hence https://graphqlite.thecodingmachine.io/docs/file-uploads will not process the `ServerRequest ` before handing it off to the `WebonyxGraphQLMiddleware`.

When using postman make sure you send a query in a single line.
