### ISSUE TITLE
Updating Packagist and docs website for latest version

### ISSUE THREAD

**Issue by oojacoboo** [thecodingmachine/graphqlite#370]
Packagist isn't being properly updated with a tagged version.  It doesn't seem there is a git hook setup for this.  I'm unsure of the permissions for Packagist as I do not have the access credentials for the service.

The docs website isn't updated for the latest version, 4.2.  I'm unsure of the requirements for this.  I was under the assumption that the `doc_generation` workflow for the docs would handle the full update.  That's apparently not the case.  I haven't been able to dig into this further.

@moufmouf your assistance is needed here with these items.

**Comment by francescolaffi** [comment]
looking forward to using 4.2 as it has useful features. I guess this is also blocking the update of the bundle? 
any non convoluted way to use 4.2 meanwhile?

**Comment by hjerichen** [comment]
In the tag of 4.2 the comsposer.json contains this line `"version": "dev-master",`
As of my understanding, this should not be there. Maybe this is the problem?

**Comment by moufmouf** [comment]
This might be related to:

![image](https://user-images.githubusercontent.com/1290952/130792533-f44a7160-b71d-4be5-9a48-705abb2305cf.png)

![image](https://user-images.githubusercontent.com/1290952/130792575-e2a155f8-3445-473e-8df9-40e588faedb4.png)

**Comment by moufmouf** [comment]
The problem is caused by this commit:

https://github.com/thecodingmachine/graphqlite/commit/32c6ea1ece7519f08dfa4a009f02823ef230456d

We should probably rollback it. I understand it is needed to run integration tests, so maybe we could add this line back in composer.json dynamically in CI?

**Comment by TamasSzigeti** [comment]
> The problem is caused by this commit:
> 
> 
> 
> https://github.com/thecodingmachine/graphqlite/commit/32c6ea1ece7519f08dfa4a009f02823ef230456d
> 
> 
> 
> We should probably rollback it. I understand it is needed to run integration tests, so maybe we could add this line back in composer.json dynamically in CI?

Sorry about that. Yes, it should solve it. A monorepo approach would make things even more convenient imo

**Comment by oojacoboo** [comment]
I'm working on a PR for the updated docs.  I'm migrating everything to docusaurus 2.x as well.  I've already gotten everything updated/migrated, but there are quite a lot of breaking changes.

The plan is to get this PR finalized, then get the docs updated and version for 4.3.0.  Hopefully packagist will update now as well and we can wrap up this issue.

**Comment by oojacoboo** [comment]
4.3.0 is out, packagist is updating and the new docs website is launched with all archived versions.
