### ISSUE TITLE
4.2 BC break and doc outdated for scalar type mapping

### ISSUE THREAD

**Issue by francescolaffi** [thecodingmachine/graphqlite#372]
`RootTypeMapperInterface` in 4.1.2 had signature

```
public function toGraphQLOutputType(Type $type, ?OutputType $subType, \ReflectionMethod $refMethod, DocBlock $docBlockObj): OutputType;
public function toGraphQLInputType(Type $type, ?InputType $subType, string $argumentName, \ReflectionMethod $refMethod, DocBlock $docBlockObj): InputType;
```

in 4.2 has signature
```
public function toGraphQLOutputType(Type $type, ?OutputType $subType, $reflector, DocBlock $docBlockObj): OutputType;
public function toGraphQLInputType(Type $type, ?InputType $subType, string $argumentName, $reflector, DocBlock $docBlockObj): InputType;
```

This change in interface means that when upgrading to 4.2 any custom type mapper that implemented the interface becomes invalid and needs to be fixed. Although the change is quick it might be worth mentioning it in the changelog to avoid surprises, especially because its not in a major version.

In addition the documentation for custom scalar type references the old signature https://github.com/thecodingmachine/graphqlite/blob/v4.2.0/docs/custom_types.md#registering-a-custom-scalar-type-advanced

**Comment by TamasSzigeti** [comment]
The actual type `$reflector` should be `Reflector` as both `ReflectionMethod` and `ReflectionProperty` implements it

**Comment by oojacoboo** [comment]
@TamasSzigeti I don't even see where the `$reflector` is being used.  I'm not sure we can type as `\Reflector` though, as that interface is implemented by other reflection classes as well.

**Comment by TamasSzigeti** [comment]
I mean while keeping the phpdoc so Stan would be aware of it. Doesn't really matter (:
