### ISSUE TITLE
Multiple graphql endpoints

### ISSUE THREAD

**Issue by tobolleo** [thecodingmachine/graphqlite#377]
Hi, for various reasons, I would like to have two separated graphql endpoints in my Symfony app. Ideally with their own namespaces. I use Graphqlite with Symfony bundle and it seems there is not such option. Is it somehow possible to achieve this?

Thank you.

**Comment by oojacoboo** [comment]
Sure, it's possible.  Just point your webserver to 2 different front controllers and build up 2 different APIs.

**Comment by oojacoboo** [comment]
Please use the Discussions for further information about this though.  We're trying to keep issue tickets related to actual issues.
