### ISSUE TITLE
Interface signature change in 4.3.0

### ISSUE THREAD

**Issue by ivoba** [thecodingmachine/graphqlite#386]
In 4.3.0 interface signature changed from

   public function toGraphQLOutputType(Type $type, ?OutputType $subType, ReflectionMethod $refMethod, DocBlock $docBlockObj): OutputType;

to
    public function toGraphQLOutputType(Type $type, ?OutputType $subType, $reflector, DocBlock $docBlockObj): OutputType;

Its not really a breaking change but it still breaks phpstan in f.e. https://github.com/thecodingmachine/graphqlite-misc-types

I fixed this in https://github.com/thecodingmachine/graphqlite-misc-types/pull/12

**Comment by oojacoboo** [comment]
@ivoba I'm not really sure about that fix.  I think maybe you meant to post this on that other repo?

At any rate, the documentation and CHANGELOG have been updated to reflect this BC break.  It was mentioned in the release notes as well.
