### ISSUE TITLE
Implement @FailWith401 annotation

### ISSUE THREAD

**Issue by JinTotonic** [thecodingmachine/graphqlite#40]
When an unlogged user tries to call a query with `@Logged` annotation, he receives a `"Cannot query field \"foo\" on type \"Query\"."` error. 
Could be great if he receives a 401 response instead.

Temporary solution : `@FailWith(null)` (thanks @moufmouf)

**Comment by moufmouf** [comment]
I am probably going to make error throwing the default behaviour in GraphQLite 4.

Ideally, we should have a GraphQL error AND a HTTP 401. Not sure if I can do that though...

**Comment by moufmouf** [comment]
#67 generates a default error for @Logged and @Right fields now.
See the updated documentation here: https://graphqlite.thecodingmachine.io/docs/authentication_authorization

**Comment by moufmouf** [comment]
Note: the HTTP error code must be triggered by the middleware so this is not directly related to GraphQLite but to the middlewares / bundles used.
See: https://github.com/APIs-guru/graphql-over-http#status-codes

**Comment by crirus** [comment]
How can I use this @looged and @right in my code?
I added the @FailWith and I get null for type, but how can I control the logges in via Symfony?
Some config I miss?

**Comment by moufmouf** [comment]
Hey @crirus ,

It really depends on how you installed GraphQLite. If you use Symfony and the Symfony bundle, it should work out of the box. Same thing with Laravel. If you are using your own framework, you must implement 2 interfaces (as described here: https://graphqlite.thecodingmachine.io/docs/next/authentication_authorization#connecting-graphqlite-to-your-frameworks-security-module)

Then, you must register those 2 classes using

```php
// Configure an authentication service (to resolve the @Logged annotations).
$factory->setAuthenticationService(new VoidAuthenticationService());
// Configure an authorization service (to resolve the @Right annotations).
$factory->setAuthorizationService(new VoidAuthorizationService());
```

See: https://graphqlite.thecodingmachine.io/docs/next/other-frameworks#integration

**Comment by moufmouf** [comment]
This is now fixed. New Security annotation allows in depth control of the behaviour of login:

https://graphqlite.thecodingmachine.io/docs/next/fine-grained-security
