### ISSUE TITLE
Parameter 'locked' is missing for class 'FooInputType' constructor. It should be mapped as required field.

### ISSUE THREAD

**Issue by marhub** [thecodingmachine/graphqlite#410]
I have a class:

```php<?php

declare(strict_types=1);

namespace App\Graphql\Type\Input;

use App\Domain\Entity\Content\ContentDocument;
use App\Domain\Entity\Content\Group;
use Symfony\Component\Validator\Constraints as Assert;
use TheCodingMachine\GraphQLite\Annotations\Field;
use TheCodingMachine\GraphQLite\Annotations\Input;
use TheCodingMachine\GraphQLite\Types\ID;

#[Input(name: 'FooInputType', default: true)]
class FooInputType
{
    public function __construct(
        #[Field] private string $title,
        #[Field] private bool $locked,
    ) {
    }
}
```

When i send mutation using this input field and set `locked: false` i get an error: 
`Parameter 'locked' is missing for class 'FooInputType' constructor. It should be mapped as required field.`

**Comment by marhub** [comment]
IMHO problem is in `empty` at `thecodingmachine/graphqlite/src/Types/InputType.php:121` as `empty(false) === true`

**Comment by oojacoboo** [comment]
If `$locked` isn't a required field, it should have a default value, otherwise it does not know how to be constructed.

**Comment by marhub** [comment]
@oojacoboo  `$locked` is required field **( it's not nullable in my example ).**

**Comment by marhub** [comment]
Issue here is as old as PHP it self is - using `empty`.
`empty` for booleans returns true for false and false for true, see example:

```php<?php
$value = true;
var_dump(empty($value)); // false -> good
$value = false;
var_dump(empty($value)); // true -> not good
```

I've prepared pull request to address this issue:  https://github.com/thecodingmachine/graphqlite/pull/411

**Comment by marhub** [comment]
and seems to be the same problem with arrays and strings.

`{value:""}` and `{value:[]}` gets same exception.
However `$value=""` is perfectly valid string and `$value=[]` is valid array.
