### ISSUE TITLE
Lock error while introspecting

### ISSUE THREAD

**Issue by bladl** [thecodingmachine/graphqlite#420]
I have front-end that requests introspection. Sometime it fails with error:

**sem_acquire(): Failed to acquire key 0xa49ee56c: Invalid argument
On line 107 in file /vendor/symfony/cache/LockRegistry.php.**

**Comment by oojacoboo** [comment]
Hey @bladl I'm not sure how this is a GraphQLite error.  Please paste the full stack-trace.

**Comment by bladl** [comment]
> Hey @bladl I'm not sure how this is a GraphQLite error.  Please paste the full stack-trace.

Is is being catched by **set_error_handler**. It has no stack-trace. Maybe webonyx package use locks internally. Two parallel introspections without cache cause this error. Thats why nobody even noticed this

**Comment by oojacoboo** [comment]
@bladl `set_error_handler` is not used in this lib.  Without a full stack-trace, it's virtually impossible to help you further.  Please figure out the issue with your logs and provide a stack-trace.  Otherwise, I'll have to close this as irrelevant.
