### ISSUE TITLE
Input type forcing

### ISSUE THREAD

**Issue by bladl** [thecodingmachine/graphqlite#421]
As described in [https://graphqlite.thecodingmachine.io/docs/input-types#forcing-an-input-type]() I can convert graphql type **ID!** to **string** parameter.

But when I have tried to use example from docs I got expection

```

Argument #1 ($id) must be of type string, TheCodingMachine\\GraphQLite\\Types\\ID given, called in /vendor/thecodingmachine/graphqlite/src/Middlewares/ServiceResolver.php on line 42

```

My code
```

public function product(#[UseInputType('ID!')] string $id,#[Autowire] AuthService $auth, #[Autowire] Kernel $kernel): ?Product
{
}
```

**Comment by oojacoboo** [comment]
Have you tried declaring the attribute outside the method signature?  I'm not sure attributes are inferred in this way, although that would be an improvement.

**Comment by bladl** [comment]
> Have you tried declaring the attribute outside the method signature, on the function, with the required `for` and `inputType` properties?  
> 
> 
> 
> ```php
> 
> #[UseInputType(for: 'id', inputType: 'ID!')]
> 
> public function product(string $id, #[Autowire] AuthService $auth, #[Autowire] Kernel $kernel): ?Product
> 
> {
> 
> }
> 
> ```
> 
> 
> 
> I'm not sure attributes are inferred in this way, although that would be an improvement.

Attribute `#[UseInputType]` has target `Attribute::TARGET_PARAMETER` so it cannot be used for methods. Also your example has error in ide  **Method call is provided 2 parameters, but the method signature uses 1 parameters**, because `__constructor` has only one parameter `@param array<string, mixed>|string $inputType`

**Comment by oojacoboo** [comment]
@bladl Apologies, I was just translating the docs, but incorrectly here.  I haven't been using attributes yet, personally.  But, I've migrated a project we manage using GraphQLite, then dug into the issue you're mentioning here as well.  I see what you're saying.

Can you please confirm for me if `#[Autowire]` is working for you?  It shares a similar implementation and doesn't look as though it should be working either.

**Comment by bladl** [comment]
> @bladl Apologies, I was just translating the docs, but incorrectly here.  I haven't been using attributes yet, personally.  But, I've migrated a large API we manage using GraphQLite, then dug into the issue you're mentioning here as well.  I see what you're saying.
> 
> 
> 
> Can you please confirm for me if `#[Autowire]` is working for you?  It shares a similar implementation and doesn't look as though it should be working either.

Yes, `#[Autowire]` is working for me. I use this attribute widely.

**Comment by oojacoboo** [comment]
Thanks.  Can you please create a test in a PR for this?  If `#[Autowire]` is working, the annotations are being handled differently as attributes for property assignment.

`./tests/Annotations/UserInputTypeTest.php`

As you can see in these tests, an Exception is expected when a `for` property isn't assigned.  A `for` property isn't required for attributes since it's interpreted.  However, it's not presently clear where that assignment is handled, or what the actual issue is.

**Comment by Lappihuan** [comment]
```php
public function product(#[UseInputType(inputType: 'ID!')] string $id,#[Autowire] AuthService $auth, #[Autowire] Kernel $kernel): ?Product
{
}
```
you were missing the property name `inputType` since its not the default property on this attribute.

This is not a bug.
