### ISSUE TITLE
Adding support for Enum types

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/graphqlite#43]
Currently, GraphQLite has no support for GraphQL "enum" types.

This is because PHP has no native "enum" support.

Yet, there exists a number of alternatives: [myclabs/php-enum](https://github.com/myclabs/php-enum), SplEnum, [eloquent/enumeration](https://github.com/eloquent/enumeration)...

The idea would be to detect any class representing an enum and mapping it to the GraphQL Enum type.

Using **myclabs/php-enum**, code could look like this:

```php
class Status extends Enum
{
    private const ON = 'on';
    private const OFF = 'off';
    private const PENDING = 'pending';
}

class UserController {
    /**
     * @Query
     * @return User[]
     */
    public function viewUsers(Status $status): array {
        // ...
    }
}
```

The "$status" argument will automatically be mapped to an InputType named "Status" of GraphQL type enum, with 3 possible values ('on', 'off' and 'pending').

Support for major enum libraries should be built in GraphQLite, with the ability to add any other library.

**Implementation details**

To do this, we need to be able to get a hook at the root type mapping level of GraphQLite (in https://github.com/thecodingmachine/graphqlite/blob/master/src/FieldsBuilder.php#L682-L717)

We should probably replace the `toGraphQlType` method with an interface that can support many different implementation (one of which would be MyclabsEnumTypeMapper):

```php
interface RawTypeMapper {
    private function toGraphQLType(Type $type, ?GraphQLType $subType, ReflectionMethod $refMethod, DocBlock $docBlockObj): ?GraphQLType;

    private function toGraphQLInputType(Type $type, ?GraphQLType $subType, string $argumentName, ReflectionMethod $refMethod, DocBlock $docBlockObj): ?GraphQLType;
}
```

**Comment by golaod** [comment]
:+1:
