### ISSUE TITLE
Using symfony/cache 5.4.0 causes infinite loading when resolving concurrent requests

### ISSUE THREAD

**Issue by ironexdev** [thecodingmachine/graphqlite#431]
This is not really an issue to be solved here, because it appears to be solved in the following version of symfony/cache (5.4.2), but I've run into it and it might be good to know for other GraphQLite users.

When I run two (or more) concurrent requests from a client (browser) to GraphQLite server they almost never finish running (few times they actually finished after significant amount of time).

This happens only when I feed GraphQLite with Psr\SimpleCache\CacheInterface created using **symfony/cache 5.4.0**. I tested it with multiple other version and haven't had any problems. Both version 5.3.13 and 5.4.2 of symfony/cache work with concurrent requests. 

It took me some time to find out the cause, so I also created a standalone repository for reproduction and debugging https://github.com/ironexdev/graphqlite-debug

Issue might also be related to the environment - I only tested it in Docker (on ARM Mac) running PHP-FPM 8.0.10 behind Nginx

**Notes**

**1) It only happens when two or more TypeNamespaces are added** 

a) [NOT OK] Issue occurs
```
$schemaFactory->addControllerNamespace("App\\GraphQL")
    ->addTypeNamespace("whatever")
    ->addTypeNamespace("App\\GraphQL\\");
```

b) [OK] Issue does not occur
```
$schemaFactory->addControllerNamespace("App\\GraphQL")
    // ->addTypeNamespace("whatever")
    ->addTypeNamespace("App\\GraphQL\\");
```

**2) It only happens when Controller method with Input as an argument exists in ControllerNamespace**

a) [NOT OK] Issue occurs
- https://github.com/ironexdev/graphqlite-debug/blob/e1eb525ea4f3c08955ffde1cc36093c83b3094ad/backend/src/GraphQL/User/UserController.php#L10-L16
    - Controller with Input doesn't have to be used in order to resolve the request, issue occurs even when request (POST `mutation{foo}`) is handled by a different Controller

b) [OK] Issue does not occur
```
#[Mutation]
public function createUser(
    // CreateUserInput $createUserInput
): bool
{
    return true;
}
```

**Comment by oojacoboo** [comment]
@ironexdev thanks, going to close unless this issue is related to GraphQLite.
