### ISSUE TITLE
Can you please provide any documentation for Slim 4 Graphqlite Implementation.

### ISSUE THREAD

**Issue by HariSankarNayak** [thecodingmachine/graphqlite#441]
Can you please provide any documentation for Slim 4 Graphqlite Implementation.

**Comment by oojacoboo** [comment]
You might reference the following two repositories for implementation into frameworks.  This repo and lib is framework agnostic.  I don't have any specific implementation details for Slim.

https://github.com/thecodingmachine/graphqlite-bundle
https://github.com/thecodingmachine/graphqlite-laravel

You can also follow the instructions for installing without a framework, which will give you an idea of how you might implement it within your Slim app.

https://graphqlite.thecodingmachine.io/docs/other-frameworks
