### ISSUE TITLE
Symfony 6.0 support

### ISSUE THREAD

**Issue by bladl** [thecodingmachine/graphqlite#444]
Please add symfony/cache ^6.0 to dependency list

**Comment by oojacoboo** [comment]
This is already added on `master`.  We'll be tagging a release soon.

**Comment by bladl** [comment]
> This is already added on `master`. We'll be tagging a release soon.

Is **master** branch stable enough to use it in production for now?

**Comment by oojacoboo** [comment]
We don't have any known issues or bugfixes for master, so it's as stable as it's going to be unless someone reports otherwise.

**Comment by francescolaffi** [comment]
@oojacoboo the bundle has a tag for sf6: https://github.com/thecodingmachine/graphqlite-bundle/releases/tag/v5.4.0

is it possible to tag a release for this library too?

**Comment by oojacoboo** [comment]
Symfony version 6 is now supported in GraphQLite version 6.

**Comment by francescolaffi** [comment]
> Symfony version 6 is now supported in GraphQLite version 6.

And the new release have other great improvements too 🥳 
Thanks @oojacoboo, made our week better!
