### ISSUE TITLE
Circular dependencies in type mapping cause seg fault using `Input` attribute

### ISSUE THREAD

**Issue by oojacoboo** [thecodingmachine/graphqlite#449]
When the `Input` type mapper is building out the schema, if there are circular dependencies between types, you'll end up with a seg fault.

We need to review the type mapper logic and see if it's possible to predict the existence of a circular dependency and throw an exception or find a way to support them, if it's possible to have the logic look back through already processed types and see if the one being processed has been processed prior.  If so, ignore it or associate it with the type being processed as a relation (if necessary).

The current issue exists where I have the following:

```php
#[Input]
class Foo
{
    /**
     * @var Bar[]
     */
    #[Field]
    protected array $bars;
```

```php
#[Input]
class Bar
{
    #[Field]
    protected Baz $baz;
```

```php
#[Input]
class Baz
{
    #[Field]
    protected Foo $foo;
```

**Comment by oojacoboo** [comment]
@devmaslov any thoughts on this?  You wrote this `Input` type mapper implementation.

**Comment by Lappihuan** [comment]
With #466 Input Types use callables too which could fix this issue.
[explanation](https://webonyx.github.io/graphql-php/type-definitions/object-types/#recurring-and-circular-types) from graphql-php

**Comment by Lappihuan** [comment]
I actually think its that we try to get all fields before we pack the configs in a callable, since the old implementation also used a callable:
https://github.com/thecodingmachine/graphqlite/pull/466/files#diff-801f55b45a3306c52e2892331cc1e8cb5c41f5800b9d8c089d37d5e07b7c5a99L48-R49

I'm not sure how to solve getting the fields only inside the callable but also still set them on the class property to be used later in resolve...

**Comment by Lappihuan** [comment]
This should be fixed with https://github.com/thecodingmachine/graphqlite/pull/466/commits/ef0c53119b91ad3545e90d3b4b121eafebddd318
@oojacoboo can you try to confirm this?

**Comment by oojacoboo** [comment]
@Lappihuan nice.  I don't actually have any ability to test this.  I looked over the commit and it looks good.  Is this part of #466?

**Comment by Lappihuan** [comment]
yes, its in #466 
i built a test that goes as far as building the schema, since your description said thats where the segfault happend.
https://github.com/thecodingmachine/graphqlite/pull/466/files#diff-eaf66d30e18cc3db1f122fd089ce3ce52deb80fdb44218807bd3964d67e21394R2385-R2397

**Comment by oojacoboo** [comment]
Yea, saw the tests - looks good.  I don't have any way of testing this more thoroughly, as the issue was resolved by working around it.  We can close this ticket with the merge of #466.

**Comment by oojacoboo** [comment]
#466 was merged and released with version 6.  I'm closing this issue - can reopen if the issue still exists.
