### ISSUE TITLE
Unable to reference types created by factories when using InputType attribute

### ISSUE THREAD

**Issue by oojacoboo** [thecodingmachine/graphqlite#451]
If an `input` type is created using the `#[Input]` attribute, any properties that reference another input type created by a factory, are unavailable to the `InputType` type mapper.  Types should be available across type mappers.  This is maybe not a huge deal, but there is a bit of a dependency web created here, and could create a mess with certain input type designs.

**Comment by oojacoboo** [comment]
The issue goes both directions, of course.  The input types created from factories and `Input` attributes aren't accessible to the other.

**Comment by Lappihuan** [comment]
@oojacoboo is this fixed with #458 ?

**Comment by oojacoboo** [comment]
@Lappihuan yep - should be.
