### ISSUE TITLE
Inject ResolveInfo in fields/queries/mutation signature

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/graphqlite#46]
If a developer puts a "ResolveInfo" argument at any position in a @Field, @Query or @Mutation, we should fill that argument with the "ResolveInfo" of the current resolver.

For instance:

```php
class Controller {
    /**
     * @Query
     * @return User[]
     */
    public function users(string $search, ResolveInfo $resolveInfo): array {
        // ...
    }
}
```

The ResolveInfo parameter will be filled in any method annotated with @Field, @Query or @Mutation.
The ResolveInfo parameter can be put at any position eligible for an input argument (so any position except the first position in the case of some @Field annotated methods)

**Comment by moufmouf** [comment]
Ping @golaod

**Comment by golaod** [comment]
Will it have a factory pattern same as input fields? So I can do:
```php
class Selection
{
    private $info;

    /**
     * @Factory
     */
    public function create(ResolveInfo $info): Selection
    {
        return new Select($info);
    }

    public function getFields(array $allowedFields, string $parent = ''): array
    {
        $source = $this->info->getFieldSelection();
        if ($parent) {

        }
    }
}

class Controller {
    /**
     * @Query
     * @return User[]
     */
    public function users(string $search, Selection $selection): array {
        $dbContext->select(
            $selection->getFields(['id', 'name'])
        );

        if ($nested = $selection->getFields(['id', 'name']), 'child') {
            $dbContext->join('child')->select($nested);
        }
    }
}
```

Or it would be too much effort and it's just easier to wrap $info inside the query/mutation/field ?

**Comment by golaod** [comment]
When I think about it, it really may be too much effort for such rather not important need :P

**Comment by moufmouf** [comment]
Ok, I'll keep this as low priority. It is not that difficult to implement and I had already some plans to allow injecting services from the container in the parameters. I can do both issues at the same time.

**Comment by moufmouf** [comment]
@golaod I realize I just missed your comment about the factory pattern + ResolveInfo.

I see where you are going here. Indeed "ResolveInfo" is a Webonyx object that is not very easy to use and if we could wrap it in an object that is project-specific and easier to use, it would be great.

I'm not sure wrapping it in a @Factory is the best way (because @Factory are meant to be used to declare input types and ResolveInfo is definitely not an input type).

That being said, I understand the need you are expressing. I don't have a solution right now but I'll think about it.

**Comment by golaod** [comment]
No worries, not super important.

**Comment by golaod** [comment]
:+1:

**Comment by moufmouf** [comment]
@golaod You can now inject `ResolveInfo` in your queries/mutations/fields.

Documentation is available here: https://graphqlite.thecodingmachine.io/docs/query-plan

Also, you now have the possibility to hook into GraphQLite parameter analysis system and inject any kind of value you want in a method. So it is now possible to support your `Selection` example (though this requires a bit of work to set up). To do this, you need to add a "parameter mapper" class. More details here: https://graphqlite.thecodingmachine.io/docs/internals#parameter-mappers. Documentation is still a bit light about ParameterMappers so do not hesitate to ask me if you want to implement your own.
