### ISSUE TITLE
cache 

### ISSUE THREAD

**Issue by dhiabenjaber** [thecodingmachine/graphqlite#460]
can i handle cache in graphqlite with redis and if there is an example of implementation

**Comment by oojacoboo** [comment]
@dhiabenjaber GraphQLite uses psr/log interfaces.  You can use whatever you like.  I’m unsure why you’d choose to use Redis though.  There isn’t any need to cache across instances and APCU or Memcache I believe would be a better choice.

I’m out of pocket at the moment, but you can confirm the cache interfaces in the docs.

**Comment by oojacoboo** [comment]
I’m closing this issue, please use discussions for general questions.
