### ISSUE TITLE
PHP 8 Union type fails while union type in doc block works

### ISSUE THREAD

**Issue by aszenz** [thecodingmachine/graphqlite#462]
I get this error when using the output type:

```php
#[Field]
public function origin(Foo $foo): Bar|Baz
{
  return $foo->origin;
}
```

```
In TypeHandler.php line 367:

  assert($type instanceof ReflectionNamedType)
```

The output types for Bar and Baz are already defined.

Adding the union type to the docblock works:

```php
/**
* @return Bar|Baz
*/
#[Field]
public function origin(Foo $foo)
{
  return $foo->origin;
}
```

I assume this is a missing php 8 features

**Comment by oojacoboo** [comment]
@aszenz yea, we're likely missing support for this.  A PR would be great :)

**Comment by oojacoboo** [comment]
@aszenz just ran into this issue myself and confirmed that the `$type` in that assertion is an instance of `ReflectionUnionType`, which makes sense.  However, the `TypeHandler::reflectionTypeToPhpDocType` method doesn't currently support this reflection type.  It looks like we'd have to handle each of the types in the union, while this function is written for a single type.
