### ISSUE TITLE
Doctrine compatibility

### ISSUE THREAD

**Issue by sirio3mil** [thecodingmachine/graphqlite#47]
Is there any option to make compatible this [repo](https://github.com/Ecodev/graphql-doctrine) with GraphQLite?

Regards

**Comment by moufmouf** [comment]
Hey @sirio3mil ,

GraphQLite does not have support out of the box for Ecodev/graphql-doctrine, but it should be possible to write a wrapper to make the 2 work together.

You can plug external Types / InputTypes into GraphQLite using the [TypeMapperInterface](https://github.com/thecodingmachine/graphqlite/blob/master/src/Mappers/TypeMapperInterface.php).

Note that Ecodev/graphql-doctrine and GraphQLite both offer an annotation system to expose classes / entities and that GraphQLite can be used directly to expose a Doctrine entity (you don't necessarily need a third party library for Doctrine).

If you are interested in trying to connect the two, I can give you a bit of support regarding the way to create the `TypeMapper`.

**Comment by sirio3mil** [comment]
Thanks! Will be great if I can have a bit support on it, I know that I can use graphqlite for doctrine but this will imply to annotate each entity, beside using ecodev I just only need to annotate special return types as graphqlite need.

So, in order to get less code I like to try it, any help will be really appreciated.

Regards
