### ISSUE TITLE
Introduce Symfony 6 support for 5.x version

### ISSUE THREAD

**Issue by andrew-demb** [thecodingmachine/graphqlite#486]
Bumping a new major version of `graphqlite` requires updating [graphqlite-bundle](https://github.com/thecodingmachine/graphqlite-bundle) and [graphqlite-symfony-validator-bridge](https://github.com/thecodingmachine/graphqlite-symfony-validator-bridge) (in the context of Symfony application).

Unfortunately, `graphqlite-bundle` for now doesn't have maintainers which can properly support it with regular updates and/or reviewing PR from the community. Last PR's with updates for supporting Symfony 6 were merged and released only 9 days ago which unlocked some Symfony components for an update to `^6`.

P.S.: We will be very thankful for the decision about introducing not only supporting new versions of dependencies, but BC compatible bug fixes and features with a new minor release, to not force users to update their applications and libraries with support for new major version of graphqlite.
If you are open to the new minor release 5.x - it will help us for a gradual upgrade to the new version of graphqlite (we have a 5+ projects and 30+ libraries which is dependent of graphqlite).

Thank you for your work in introducing features and supporting this library.

**Comment by oojacoboo** [comment]
Hey @andrew-demb.  I'm not entirely sure what you mean with regards to a minor release here.  As I've expressed before, I do not have any interest in maintaining framework bundles/plugins/widgets/etc.  If someone is interested in doing so, they should help out.  I would never use any of these, because, in my opinion, they're entirely unnecessary dependencies.

GraphQLite should be an entirely agnostic lib, that's not influenced by downstream dependencies.  There is no reason these libs cannot be updated for GraphQLite if people are getting value out of them.

**Comment by andrew-demb** [comment]
I'm saying about releasing one more 5.x version with changes, that are not break backward compatibility (bugfixes, supporting latest versions of dependencies). Most of changes released with 6.0 could be released as another 5.x version and only BC breaking features requires major version bump.

Every major version bump requiring to review BC breaks, analyse whether consumer library can be compatible with both versions (old and new, 5.x and 6.x for now) and change dependency requirements.
While updating semver-compatible versions of dependencies are pretty safe and can be done without any human attention.

**Comment by oojacoboo** [comment]
@andrew-demb thanks for your explanation.  I understand where you're coming from.  If you'd like to submit a PR for a 5.0.3 branch off the 5.0.2 tag, I'd be happy to merge it and target a new release.  We don't have a good branching strategy at the moment to maintain and port updates like this.  And, frankly, there isn't enough time to mess with it.  I'm happy to merge in reasonable PRs along these lines if someone else wants to put it all together.

Technically, version 6.0 could have probably been a `5.1` release.  However, there are notable changes in the overall `Input` design that warrant a new full version, in my opinion.

**Comment by oojacoboo** [comment]
I've added a new `5.0` branch.
