### ISSUE TITLE
Allow psr/container v2

### ISSUE THREAD

**Issue by bladl** [thecodingmachine/graphqlite#517]
GraphqLite is failing to install with my Symfony 6 project. Some of packages require v2 of [psr/container](https://github.com/php-fig/container)
[psr/container](https://github.com/php-fig/container) v2 is required.
Tried to resolve, but [picontainer](https://github.com/thecodingmachine/picotainer) locked psr/container v1.

**Comment by oojacoboo** [comment]
I haven't looked into v2 for `psr/container`.  Is there anything substantial that's changed?

**Comment by bladl** [comment]
> I haven't looked into v2 for `psr/container`. Is there anything substantial that's changed?

Seems like just a boolean type hint was added https://github.com/php-fig/container/releases/tag/2.0.0

**Comment by bladl** [comment]
According to this [deprecation warning](https://github.com/container-interop/container-interop#deprecation-warning). 
[Container intertop](https://github.com/container-interop/container-interop#deprecation-warning) used by [picontainer](https://github.com/thecodingmachine/picotainer)  is already deprecated in favor of psr/container

My proposal is to replace picontainer with a custom one based on psr/container.
Would be glad to make a PR!

**Comment by bladl** [comment]
Seems like this repository is abandoned. Issues not reviewed for a 6 months https://github.com/thecodingmachine/picotainer/issues/8
