### ISSUE TITLE
Nested `Input` annotated types within `Factory` defined inputs causes type conflicts

### ISSUE THREAD

**Issue by oojacoboo** [thecodingmachine/graphqlite#537]
See #532.  

Currently, factories require a `Type` annotation on the target class.  This is problematic if a field of that class is typed as an `Input` type.  One possible solution here would be to update the factory logic to require an `Input` attribute.  To be compatible with the existing input type mapping, we'd need to add a custom parameter on the `Input` attribute, to denote that the input type is created with a factory.

I also think we could probably just get rid of the `Factory` attribute, altogether and have the `Input` property point to the factory method instead.

I think for most people, a factory isn't needed at all.  A constructor on a DTO style `Input` defined class is more than sufficient.

Consider the following, where `factory` takes a callable.

```php
#[GraphQLite\Input(factory: [FooInputFactory::class, 'build'])
class FooInput
{
    public function __construct(
        public readonly ID $id,
    ) {}
}

class FooInputFactory
{
    public function build(ID $id): FooInput
    {
        return new FooInput($id);
    }
}
```

**Comment by mdoelker** [comment]
Can you give a code example to better understand the problem? I have many factories in use that map input types to models just fine. You mentioned in #532 however that the issue could be linked with using input types within input types, so that might be the problematic combination.

**Comment by oojacoboo** [comment]
@mdoelker Building off that last example.  Here is how it is currently.  You cannot mix factories and Input annotated classes together.  A factory requires that you annotate the input type class with a `Type` annotation.  Which is really wrong.  That should be for an output type, not an input type.  And, I haven't checked the schema to check, but it's possible it's also generating an output type for that class as well.

```php
#[GraphQLite\Type)
class FooInput
{
    public function __construct(
        #[GraphQLite\Field]
        public readonly ID $id,
    ) {}
}

class FooInputFactory
{
    #[GraphQLite\Factory]
    public function build(ID $id): FooInput
    {
        return new FooInput($id);
    }
}

#[GraphQLite\Input)
class BarInput
{
    public function __construct(
        #[GraphQLite\Field]
        public readonly ID $id,

        #[GraphQLite\Field]
        public readonly FooInput $foo,
    ) {}
}
```

**Comment by mdoelker** [comment]
That said, I'm not sure about the `BarInput` use case where a field is another input type. I never had the need to do that, but this seems like it should be supported. I will try this later.

**Comment by oojacoboo** [comment]
@mdoelker That's correct.  I removed the `#[Field]` attribute that was on the `FooInput` class.  That isn't needed.

As for the `Type` or the `Input` annotation needing to be on the target class - yea, they're pointless really, as the `Factory` is what is defining the actual input type.  At any rate, requiring a `Type` annotation, as it currently is, is certainly not ideal.

All of this is a result of factories being the only way you could create input types, initially.  The `Input` annotation didn't exist, so the `Type` annotation was used.  In that context, it makes sense.  Technically, both input and output are types.  However, as it is now, a `Type` annotated class is really an output and `Input` is an input.

But yea, the issue is when you're mixing them with a nested input, which is what happened in our case as we began slowly migrating from factories to using `Input` annotated classes.

**Comment by oojacoboo** [comment]
Maybe we should just remove the requirement for a target class to have any annotations at all, and solely rely on the `Factory` annotated method.  That would be a BC friendly change that should resolve the nested input type issue as well.

**Comment by mdoelker** [comment]
In my example above, which represents how I use factories in my codebase, the target class has no annotations and knows nothing about graphqlite. So that works perfectly well already.

**Comment by oojacoboo** [comment]
@mdoelker hmm, maybe it was only requiring the annotation because of the nested input then.  We've now migrated all our factories over to `Input` annotated classes and the issue no longer exists.  I guess nested inputs really aren't going to be all that common and mixing `Input` annotated classes with `Factory` built inputs is also less likely.

We need a testcase to replicate this issue.
