### ISSUE TITLE
Webonyx v15

### ISSUE THREAD

**Issue by bladl** [thecodingmachine/graphqlite#540]
`webonyx` v15.0 is out. 
https://github.com/webonyx/graphql-php/releases/tag/v15.0.0

Will be both v14 and v15 supported by `graphqlite`? At first glance there is backward-incompatible changes

Bumping a new major version of `webonyx` requires updating [ecodev/graphql-upload](https://github.com/thecodingmachine/graphqlite-bundle) first.

**Comment by oojacoboo** [comment]
[ecodev/graphql-upload](https://packagist.org/packages/ecodev/graphql-upload) doesn't support webonyx v15 yet.  So, we would need to wait for support there first.

Outside of that, their update notes don't make it very clear what's likely to be broken... I guess anything "changed".  But there is a lot of smaller things there that aren't likely to be a BC break.

We could start with a PR that updates the dep, see what's breaking and go from there.

**Comment by PowerKiKi** [comment]
`ecodev/graphql-upload` has been released with `webonyx/graphql-php` 15 support: https://github.com/Ecodev/graphql-upload/releases/tag/7.0.0

**Comment by oojacoboo** [comment]
@PowerKiKi thanks for that!
@bladl want to give a PR a shot, updating the deps - see what we're looking at?

**Comment by oojacoboo** [comment]
@PowerKiKi was there a specific reason for PHP 8.1 minimum support and not 8.0?

**Comment by PowerKiKi** [comment]
All my projects are on PHP 8.1, and I am not not keen of the extra mental burden to support multiple PHP versions. I don't even have PHP 8.0 installed anymore. And 8.0 will be EOL quite soon in 10 months, so I don't think it's doing anyone any favor to start using something that will soon be deprecated.

According to https://packagist.org/php-statistics, PHP 8.0 is "only" ~25% of all PHP 8+, and I expect it would go decrease even more with the adoption of the recent 8.2 in the coming months.

**Comment by oojacoboo** [comment]
@bladl @PowerKiKi thanks guys!  It's been merged.
