### ISSUE TITLE
Porpaginas is not maintained

### ISSUE THREAD

**Issue by rusted-love** [thecodingmachine/graphqlite#547]
I have weird notices such as `Porpaginas\Result::count() should either be compatible with Countable::count()` while running  tests in `graphqlite`
Look at https://github.com/beberlei/porpaginas/pull/23 
This PR is not being merged for a 5 month

Should we drop `beberlei/porpaginas` and replace it with own `graphqlite` pagination helper?

Seems like with next major php version we will be forced to do so

**Comment by oojacoboo** [comment]
Let's see if we can get it merged and tagged.  But if not, yea - probably need to look at bringing that into the lib and remove an external dependency.

**Comment by oojacoboo** [comment]
@bladl it's now merged and 2.0 tagged.

https://github.com/thecodingmachine/graphqlite/pull/558 was just created as well.  I assume we don't need to maintain 1.2 support here.

**Comment by rusted-love** [comment]
Im glad to see `beberlei/porpaginas` still alive after a long time.
