### ISSUE TITLE
Improve #[InjectUser] to throw authentication errors

### ISSUE THREAD

**Issue by oprypkhantc** [thecodingmachine/graphqlite#572]
`#[InjectUser]` can be improved further to throw a `MissingAuthorizationException` when a user is not authenticated, to avoid adding `#[Logged]` when user is required anyway, i.e.:

```php
#[Query]
public function someQuery(
    #[InjectUser] User $user, // <-- here a user is required (because the type isn't nullable), so it doesn't make sense to fail with a 500 internal error when a query isn't annotated with #[Logged]
): void {}
```

Obviously this should not apply to nullable or optional parameters:

```php
#[Query]
public function someQuery(
    #[InjectUser] ?User $user, // <-- user is not required, so it's assumed to be optional
    #[InjectUser] User $user2 = new User(), // same here, it has a default value so it's assumed optional
): void {}
```

This improvement will be easy to implement: 
 - add a `$optional = $parameter->isOptional() || $parameter->getType()?->allowsNull();` check in [InjectUserParameterHandler](https://github.com/thecodingmachine/graphqlite/blob/master/src/Mappers/Parameters/InjectUserParameterHandler.php#L33)
 - add a check to throw an exception if a user is missing in [InjectUserParameter](https://github.com/thecodingmachine/graphqlite/blob/master/src/Parameters/InjectUserParameter.php#L22)

I'll PR this improvement if it's desirable. Thoughts?

**Comment by Lappihuan** [comment]
sounds good, i'd probably not rely on it to replace logged but we manage that in our custom middleware anyway.
