### ISSUE TITLE
First party support for `void` return type

### ISSUE THREAD

**Issue by oprypkhantc** [thecodingmachine/graphqlite#573]
Currently if you try to return `void` from a mutation (as it the case with "delete" type of mutations), you get an error for being unable to map the `Void_` type. Because this is a common and valid use case for PHP, I believe it should be supported by `graphqlite` natively, the same way as `DateTime` is natively supported:

```php
#[Mutation]
public function deleteSomeEntity(SomeEntity $entity): void
{
    $entity->delete();
}
```

It's a somewhat [common practice](https://the-guild.dev/graphql/scalars/docs/scalars/void) to add a scalar type `Void` to handle such cases. This can be done in `graphqlite` too with a root type mapper.

As always, if this is desirable, I can PR this improvement. Thoughts?

**Comment by oprypkhantc** [comment]
Perfect :)

**Comment by oojacoboo** [comment]
I agree - would be a great addition to the base types.  We've been returning `true` in these cases, which really isn't nearly as desirable.
