### ISSUE TITLE
doctrine/annotations should be upgraded to v2

### ISSUE THREAD

**Issue by rusted-love** [thecodingmachine/graphqlite#579]
Currently I have issues with installation of php cs fixer version `3.13` and higher in my project. 
It requires `doctrine/annotations` `v2`.
There have been a failing tests for auto upgrade using dependabot. 
https://github.com/thecodingmachine/graphqlite/pull/552

So, should we target minimum version `v2`?

`php-cs-fixer v3.15.0` is important because it has stable php 8.2 support

**Comment by oprypkhantc** [comment]
Just as a side note, you can use `php-cs-fixer/shim`. It's the same fixer but packaged into `.phar`, so it has no dependencies at all, just like `phpstan/phpstan`. Works wonders :)

**Comment by rusted-love** [comment]
@oprypkhantc Wow, thats really helpful note! Thank you 😅
