### ISSUE TITLE
New patch version

### ISSUE THREAD

**Issue by utnaf** [thecodingmachine/graphqlite#596]
Hi! We are testing the [6.0beta.0 bundle](https://github.com/thecodingmachine/graphqlite-bundle/releases/tag/v6.0.0-beta.0) and the 6.2.2 version will include the support for doctrine/annotations:1.14, is there a plan or a deadline for releasing a 6.2.2? Or do we have to wait for 6.3.0?

Thanks

**Comment by oojacoboo** [comment]
We can tag a 6.2.2 release.  I need a few days though.

**Comment by utnaf** [comment]
Really appreciated

**Comment by oojacoboo** [comment]
Done.  https://github.com/thecodingmachine/graphqlite/releases/tag/v6.2.2
