### ISSUE TITLE
Arguments description in schema

### ISSUE THREAD

**Issue by downace** [thecodingmachine/graphqlite#622]
Currently description is not supported for fields arguments.

I've tried to implement my own [parameter middleware](https://graphqlite.thecodingmachine.io/docs/argument-resolving#writing-the-parameter-middleware) which takes description from the DocBlock:

```php
// snip
if ($mappedParameter instanceof InputTypeParameter) {
    $paramTag = \Arr::first(
        $docBlock->getTagsByName('param'),
        fn(Param $paramTag) => $paramTag->getVariableName() === $parameter->getName(),
    );

    $desc = (string) $paramTag?->getDescription();

    $mappedParameter->setDescription($desc);
}
// snip
```

<details>
<summary>Expected result example</summary>

```php
class ProductController {
    /**
     * @param ID $id The product id
     */
    #[Query]
    public function product(ID $id): Product {
        // ...
    }
}
```

```graphql
type Query {
  product(
    "The product id"
    id: ID!
  ): Product!
}
```

</details>

But it's not working. I found that parameter description is ignored when creating QueryField from Descriptor, here:

https://github.com/thecodingmachine/graphqlite/blob/8d6a29248d7dc366815ce5e8677bd1e97bb9ae0b/src/InputTypeUtils.php#L115-L124

**Comment by oojacoboo** [comment]
@downace a PR would be welcomed for support.  Does this include output type fields?  An implementation should cover all field arguments.

**Comment by downace** [comment]
> @downace a PR would be welcomed for support

Sure, working on it.

> Does this include output type fields? An implementation should cover all fields, not just input type fields.

AFAIK, descriptions are currently supported everywhere (via DocBlocks or annotation's `description` parameter) except fields arguments.

**Comment by oojacoboo** [comment]
> AFAIK, descriptions are currently supported everywhere (via DocBlocks or annotation's `description` parameter) except fields arguments.

Yes, but fields can have arguments for input and output types, and those are two different types, which have different type mappers IIRC.
