### ISSUE TITLE
Add support of types from vendor packages

### ISSUE THREAD

**Issue by fogrye** [thecodingmachine/graphqlite#657]
This is mainly for input types but could be considered for output also. 

While you can use classes from various libraries you are limited to only current project folders in case you moved some input types to external package. In my case I have some where/sort classes + logic moved as shared library and want to have them used as types, I have added all attributes but SchemaFactory will ignore them as GlobClassExplorer only looks into project src.

I'm happily contribute to this one + https://github.com/thecodingmachine/class-explorer but that is a big change for class explorer and maintainers of that lib may not be happy about it.

I hope my request to support vendor packages types will find supporters as IMHO it's must have for complex projects. 

Happily receive any feedback on this, thx.

**Comment by oojacoboo** [comment]
@fogrye Can you not just include the namespace for these classes in the `SchemaFactory` configuration?

```php
SchemaFactory:: addTypeNamespace('Vendor\\Namespace');
```

**Comment by fogrye** [comment]
@oojacoboo I wish so, but as readme in class explorer says - it just goes through project files but not also vendor files. Thats why I want to suggest this feature here and in class-explorer project.

**Comment by oojacoboo** [comment]
Not exactly sure why that'd be the case, or how vendor files would be specifically ignored.  But if that's the case, it sounds like the PR belongs on `class-explorer` lib.  Unfortunately, I do not have any maintainer permissions on that repo.  But I'm guessing they won't have any issues with it, maybe with an option, if it's a performance consideration.  I don't don't where GraphQLite would be configuring which files are "src" files and which ones are "vendor" files, such that `class-explorer` would know the difference.  But maybe it just explicitly ignores vendors somehow.

**Comment by fogrye** [comment]
@oojacoboo so seems to me that `class-explorer` is kinda dead, I found that @moufmouf was working on something what I actually need [here](https://github.com/thecodingmachine/class-explorer/pull/1/files) but haven't finished his work. What do you think if I will finish that and we change dependency for this project to my fork?

**Comment by fogrye** [comment]
@oojacoboo I found a couple but not that good:
- https://packagist.org/packages/haydenpierce/class-finder - nice one but we'll loose psr-0 support
- https://packagist.org/packages/waylandace/class-finder - small fork of already unmaintained project with is not much better than what we have

I'm personally more for 1st option, what do you think?

**Comment by oojacoboo** [comment]
@fogrye @oprypkhantc suggested looking at https://github.com/alekitto/class-finder/ as well.  Looks like it supports Composer, which would be PSR0/4, etc.

**Comment by fogrye** [comment]
@oojacoboo so could you pls check the MR, I believe we can have it merged

**Comment by oojacoboo** [comment]
Thanks again - merged.
