### ISSUE TITLE
Time to drop annotations

### ISSUE THREAD

**Issue by fogrye** [thecodingmachine/graphqlite#675]
### Discussed in https://github.com/thecodingmachine/graphqlite/discussions/673

<div type='discussions-op-text'>

<sup>Originally posted by **fogrye** March 29, 2024</sup>
Doctrine annotations was deprecated since php 8.0 release, should we drop support of them as php7 is not supported and there are no other reason not to use attributes?</div>
Steps to do:

- rm attributes from fixtures
- polish annotation classes
- rm lib from dependencies

I will create MR for this soon

**Comment by oojacoboo** [comment]
Looking forward to it @fogrye
