### ISSUE TITLE
Update cache-utils library

### ISSUE THREAD

**Issue by sudevva** [thecodingmachine/graphqlite#693]
Hey, guys. I'm pretty sure I'm writing to wrong repository, but there is the issue with caching library, that no one care in that repo.
I'm just trying to speed up the process)

https://github.com/thecodingmachine/cache-utils/pull/8

Thank you!

**Comment by oojacoboo** [comment]
So, I don’t have any write access over there, only this repository.  We’ve had similar issues on other repos that were added like this and it’s really just best we replace them with something that’s actually managed.  It looks like this is the last dependency.

A PR to replace this lib with another cache lib or by using a PSR compatible cache interface that’s set through the config, would be ideal.

**Comment by xyng** [comment]
@oojacoboo thank you for outlining the required change. I have prepared a (simple) pr that removes the packages and its ttl functionality while providing a way to support a fork of that package.
