### ISSUE TITLE
It's time to release 7.1 :)

### ISSUE THREAD

**Issue by SCIF** [thecodingmachine/graphqlite#707]
There are 22 commits in master since 7.0.0 so I assume it worth to release these improvements.

**Comment by andrew-demb** [comment]
In unreleased commits, there's dropped support for Doctrine annotations and minor BC breaks. I suggest tagging it as a `7.1.0`

**Comment by SCIF** [comment]
Hi @andrew-demb , that's correct and I had the same intention of releasing the new version as you did — introduce support of v7 Symfony by a bundle repo

**Comment by jaapio** [comment]
According to the semversion standard you shouldn't do any bc breaks in minor versions. I didn't check the changes. But if there are breaking change done, please tag the new version as 8.0.0. 

When needed I would be happy to help testing a pre release to find any breaking changes.

**Comment by enricobono** [comment]
Hello @nguyenk, @homersimpsons.
Is there anything still missing to release 7.1?
I guess this will unlock @andrew-demb to reach compatibility with Symfony 7, isn't it?

Let me know if I can help with some code contribution :)

**Comment by andrew-demb** [comment]
@enricobono it should be released as 8.0.0.

This will unlock migration to the major version of graphqlite (current graphqlite 7.0.0 cannot be used to update - some things required to be fixed and there is additional BC breaks in master branch) for graphqlite-bundle

Update to Symfony 7 is possible with graphqlite 6 - https://github.com/thecodingmachine/graphqlite-bundle/pull/227

**Comment by enricobono** [comment]
Thanks @andrew-demb 

Re:
> Update to Symfony 7 is possible with graphqlite 6 - [thecodingmachine/graphqlite-bundle#227](https://github.com/thecodingmachine/graphqlite-bundle/pull/227)
The PR you mentioned here is not merged yet, so I guess we cannot use graphlite 6 with Symfony 7 at the moment, am I right?

**Comment by oojacoboo** [comment]
Apologies in the delays in getting out this release.  [8.0.0 has just been tagged](https://github.com/thecodingmachine/graphqlite/releases/tag/v8.0.0)
