### ISSUE TITLE
Why mapClassToType return MutableObjectType

### ISSUE THREAD

**Issue by Big-Shark** [thecodingmachine/graphqlite#71]
Method "[mapClassToType]( https://github.com/thecodingmachine/graphqlite/blob/master/src/Mappers/StaticTypeMapper.php#L80)" return "MutableObjectType", but "[mapNameToType](https://github.com/thecodingmachine/graphqlite/blob/master/src/Mappers/StaticTypeMapper.php#L135)" return "Type"
and I can do this
```
    /**
     * @Field(outputType="Amount")
     */
    public function getEmail()
    {
        return $this->amount;
    }
```
But I can't do this
```
    /**
     * @Field
     */
    public function getEmail(): Amount
    {
        return $this->amount;
    }
```
Maybe I try to work wrong with Scalar Types?

**Comment by moufmouf** [comment]
Hey  @Big-Shark ,

I'm not sure I understand your issue. Was this issue solved by the PR you opened here? (https://github.com/thecodingmachine/graphqlite-bundle/pull/16)

Can I close this or do you still have a problem here? If you still have a problem, could you explain more in detail what it is?

Thanks!

**Comment by Big-Shark** [comment]
@moufmouf This is related to my PR, but I used a fixed version for test.
I can try use [Custom Scalar Types](https://webonyx.github.io/graphql-php/type-system/scalar-types/), but I can not find documentation about this, and I use this hook.
I create class 
```
class AmountScalarType extends ScalarType
{
    /** @var string */
    public $name = 'Amount';
...
}
```
And in me getter I write this
```
    /**
     * @Field(outputType="Amount")
     */
    public function getAmount()
    {
        return $this->amount;
    }
```
And this is working (serialize function calling and change value) correctly, but this generates the wrong schema and would prefer to use return type hint.
How can I create Custome Scalar Type and use it?

**Comment by moufmouf** [comment]
Hey @Big-Shark ,

Documentation in GraphQLite is here: https://graphqlite.thecodingmachine.io/docs/next/custom-types#registering-a-custom-scalar-type-advanced

The feature is quite new (it was developed last month). It is part of GraphQLite 4 (there is no stable release yet, I'm planning on tagging a release next month probably).

**Comment by Big-Shark** [comment]
@moufmouf oh, this is a little bit help me, by now I have another question,
I have scalar type Currency, and this is a simple string in my php app,  and my method
```
     * @Field(outputType="Currency")
     * @return string
     */
    public function getDefaultCurrency(): string
    {
        return $this->defaultCurrency;
    }
```
works very good, but when I try return currency array, this is return mistake 'Syntax Error: Expected <EOF>, found [' 
```
    /**
     * @Field(outputType="Currency[]")
     * @return string[]
     */
    public function getAvailableCurrencyList(): array
    {
        return $this->availableCurrencyList;
    }
```
What do you think about this? And how I can use graphql scalar type with simple php scalar type?

**Comment by Big-Shark** [comment]
@moufmouf Sorry, I am bad,
```
@Field(outputType="[Currency]")
```
works.

**Comment by moufmouf** [comment]
Excellent. Also, I don't know if you noted, but you can create value objects in PHP (a Currency class) that will be automatically mapped to the Currency scalar type in GraphQL.

If you like using value objects, it can be useful. To do so, you need to define a "RootTypeMapper".

**Comment by Big-Shark** [comment]
> Excellent. Also, I don't know if you noted, but you can create value objects in PHP (a Currency class) that will be automatically mapped to the Currency scalar type in GraphQL.
> 
> If you like using value objects, it can be useful. To do so, you need to define a "RootTypeMapper".

thx, I know this, but now I use simple scalar type in php.
